glific/glific

.github/workflows/continuous-integration.yml
- Upgraded Postgres image version from 11 to 12 in Github action for CI.
=> Upgraded CI postgres image version from 11 to 12

lib/glific/messages.ex
Currently, if we filter the conversation using exclude tag filter it did not return any results if there is no entry in the message_tag table.
=> Conversation API issues with exclude tag filter

lib/glific/communications/message.ex, lib/glific/enums/constants/enums.ex, lib/glific/enums/enums.ex, lib/glific/messages.ex, lib/glific/messages/message.ex, lib/glific_web/schema/message_type.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, test/glific/communications_test.exs, test/glific_web/schema/message_test.exs
#161 
- Added new enum for message status
- Added new field status in message schema
- Removed provider_id and provider_status from graphql message input and updated test cases for that
- Doctest update for message status enum
- Communication test while sending the message to the output contact
=> (#161) send message to provider

api.docs/includes/_auth.md, config/config.exs, lib/glific/contacts.ex, lib/glific/messages.ex, lib/glific/providers/gupshup/message.ex, lib/glific_web/controllers/api/v1/registration_controller.ex, lib/glific_web/router.ex, priv/repo/seeds_prod.exs, test/glific/contacts_test.exs, test/glific_web/registration_controller_test.exs
1. Now front end can validate phone number before calling send OTP API.
2. Using hsm template for OTP
3. Fix for contact optin
4. Check for contact opted in.
5. OTP expiry time from passwordless auth config
=> Validate phone API

api.docs/includes/_organizations.md, api.docs/includes/_scalars.md, assets/gql/organizations/fields.frag.gql, lib/glific/partners/organization.ex, lib/glific/partners/out_of_office.ex, lib/glific_web/schema/organization_types.ex, priv/repo/migrations/20200812122802_alter_glific_tables.exs, test/glific/partners_test.exs, test/glific_web/schema/organization_test.exs
1. Added schema for out of office and enabled days
2. Prepare enabled days list before inserting to the database, if data for all days is not provided
3. Default values for out_of_office settings
4. Tests and docs update
=> Feature: organization settings for out of office feature

lib/glific/flows.ex, test/glific/messages_test.exs
1. Fix for order by.
2. Fix for listing a flow multiple times.
3. Getting filtered flows that have flow revision stored with the status at least once.
=> Fix for order by in list flows API

lib/glific/contacts.ex, lib/glific/flows.ex, lib/glific/groups.ex, lib/glific/jobs/bigquery/bigquery_worker.ex, lib/glific/messages.ex, lib/glific/searches.ex, lib/glific/tags.ex, lib/glific/templates.ex, lib/glific/users.ex, lib/glific_web/resolvers/contacts.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/resolvers/groups.ex, lib/glific_web/resolvers/messages.ex, lib/glific_web/resolvers/searches.ex, lib/glific_web/resolvers/tags.ex, lib/glific_web/resolvers/templates.ex, lib/glific_web/resolvers/users.ex, lib/glific_web/schema/middleware/add_organization.ex
1. Removing helper for get_org_filter in resolvers,
2. Removing the signature of filter of organization id in context's list and count functions.
3. Removing put_organization_id in middleware
=> Remove organization id in filter from resolvers and contexts

lib/glific/flows.ex
#800 
Added a check for nil BSP limit 
We still need to put a default bsp limit as 1 instead of nil.
=> adding check for bsp limit

lib/glific/cors_proxy.ex, lib/glific/providers/gupshup/contacts.ex, lib/glific_web/controllers/api/v1/cors_controller.ex, lib/glific_web/router.ex
Currently, we are using a Heroku library to show all the previews in the messages. Because of the per-minute request limitations in the library sometimes preview does not show up. 
That's why I implemented a proxy server. 
I borrowed the idea from https://github.com/bcentinaro/cors-proxy
=> CORS Proxy

lib/glific/providers/gupshup/message.ex
Gupshup does not allow null values in the caption. So I converted it to an empty string.
=> glific updates

lib/glific/flows/action.ex
Since flow context is a struct and does not implement access behavior, we can not use get_in/2 to get the value.
=> Optin status 

lib/glific/bigquery.ex
Increased the update/delete interval to 3 hours to take care of streaming buffer error
=> Increasing the delete interval to handle streaming error on Bigquery

lib/glific_web/flows/flow_editor_controller.ex, test/glific_web/flows/flow_editor_controller_test.exs
Creating duplicate returns an error message along with an error generated in appsignal
=> sending error message when duplicate contact field is created

assets/gql/flows/export_flow.gql, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific_web/schema/flow_test.exs
Added a graphql endpoint to return the latest flow definition for a given `flow_id`
1. Tested it on the Absinthe Playground by running the following graphql query:
```javascript
query {
exportFlowDefinition(id:1) {
definition
}
}
```
It gave the response as expected (screenshot below)
2. Ran the test `mix test test/glific_web/schema/flow_test.exs:98` and got a success
=> initial commit for the export flow feature

config/.env.test, config/runtime.exs, lib/glific/third_party/navanatech/navanatech.ex, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
- Removed Navana tech config from runtime to org-specific credentials.
- This will also help us to change the base URL quickly whenever we need to.
=> Clean the APIs

lib/glific/partners/invoice.ex, test/glific/partners/invoice_test.exs
- added check for validating billing in webhook in case of organization that have not put card details or have removed it but are in Stripe portal
=> added check for validating billing in webhook

lib/glific/partners/billing.ex
- Added log when updating metered usage in stripe billing
- return `:ok` when no stats available
=> Stripe: update metered user usage

lib/glific/flows/webhook_log.ex, test/glific/flows/webhook_test.exs
Using `or` instead of `and` in the filter for webhook logs
=> Webhook Logs: using or in filters

lib/glific/clients/sol.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
- Added bq inserted_at to make the selection of most recent rows in the storage. 
- We saw that there are a few cases where the updated_at and inserted_at are the same. So this field will help in case of those issues as well.
=> Bigquery Added inserted at

lib/glific/repo.ex
Fetching provider by shortcode was giving two results (gupshup  and gupshup enterprise)
Now we will match shortcode strictly.
=> Gupshup credentials fixes

lib/glific/communications/message.ex
We throw this error when we have sent the message without a BSP id.
=> could not update bsp messages

lib/glific/communications/mailer.ex
closes #2220 
closes #2219
Clean the subject before sending it to the mail.
=> Remove new line from the subject. 

lib/glific/templates.ex
- Set example as "NA" if it's not found.
=> Example is not mandatory while fetching the HSM form BSP 

lib/glific/flows/templating.ex
There is a bug in the flow editor that sometimes it's sending the extra params in case of session templates. I have fixed it from a API perspective for now. 
=> HSM template fixes 

lib/glific/seeds/seeds_dev.ex, lib/glific/users.ex, priv/repo/seeds/20200723172939_add_glific_data.exs, test/glific/access_control_test.exs, test/glific_web/schema/role_test.exs, test/glific_web/schema/user_test.exs
There are 4 roles by default in the table Roles for each organization and then there is a user roles table where mapping is done for each role to each user
Right now these 4 roles are not populated in the new organization setup.
=> Roles and Permission: Seeder Fixes

priv/repo/migrations/20220826061242_add_profile_id_to_flow_tables.exs
Target issue is #2404  
-  Added profile id to messages table
-  Added profile id to flow results table
-  Added profile id to flow contexts table
-  Added profile id to contact history table
-  Added trigger to update profile ids on new insertion
=> Profiles: storing profile level info across tables

lib/glific/saas/onboard.ex, test/glific/partners/onboard_test.exs
We recently switched to Partner API to submit the templates. We missed this edge case. 
Disabling the common otp template submission while onboarding an org.
=> Disable automatic template approval for new organization

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
Target issue is #2510   
- Added support to sync group level info in messages table to BigQuery
=> Bigquery: Syncing message groups

lib/glific/templates/interactive_template.ex, test/glific/templates/interactive_template_test.exs
Target issue is #2528   
This adds ecto constraints so that errors creating an interactive template will result in an error message rather raising an Ecto.Constraint Error
- [n/a ] In the case of adding a new API, you added a **postman** request for that.
-----------
Note: I'm making this contribution as part of the HacktoberFest initiative. If you wish to signal this as a valid contribution label this PR with hacktoberfest-accepted. Thank you.
=> Adds Ecto constraints to the interactive template #2528

lib/glific/flows/contact_action.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, test/glific/flows_test.exs
- replace action.uuid to action.node_uuid to message table.
=> Contact actions add node id instead of action uuid to message

lib/glific/clients.ex, lib/glific/flows/action.ex
Dynamic labels were not working for in interactive messages.
=> Dynamic labels were not working for in interactive messages.

lib/glific/third_party/bigquery/bigquery_worker.ex
Target issue is #2607 
Added timeout to query while syncing data to BQ.
**Screenshot**
Query timeout while syncing data
=> Bigquery: increasing timeout for max_last_update

lib/glific_web/controllers/api/v1/session_controller.ex, lib/glific_web/router.ex, test/glific_web/session_controller_test.exs
Target issue is #2643 
At the request of our friends from the frontend
=> add a new REST API endpoint to get the name of an org

assets/gql/messages/send_hsm_message.gql, lib/glific/messages.ex, test/glific_web/schema/message_test.exs
The target issue is #2473 
Cleaning the HSM params (Removing the new lines and extra spaces) before sending it to gupshup. 
Before submitting a pull request, please ensure that you mark these tasks.
=> Clean the hsm message params as per waba rule

lib/glific/flows/contact_action.ex
#2670 
1. Parse message body for the sheet interactive messages
**Note** - After fixed added, I checked all the interactive messages and working fine
=> #2670 interactive message bug fix

lib/glific_web/flows/flow_editor_controller.ex
Added sheet type in the floweditor sheet API. This is needed to filter out the sheets the link sheet node.
=> Added sheet type in the floweditor sheet API

lib/glific/clients/tap.ex
Added fix for the space after comma
**Fixes:**
1. Used String.trim(school_name)  to remove any leading or trailing whitespace from the school name before splitting it. 
2. Added the regular expression ~r/[,\s]+/ is used as the splitting pattern, which matches one or more commas or whitespace characters.
=> School name fix for - TAP

lib/glific/messages.ex, lib/glific_web/schema/message_types.ex, test/glific/messages_test.exs
Target issue is #2885 
- Add new field called `types` in message filter
- Updated corresponding query
- Added testcases for filtering message using `types`
=> Messages: Updated API to filter using list of message type

lib/glific/communications/mailer.ex, lib/glific/mails/balance_alert_mail.ex, lib/glific/mails/critical_notification_mail.ex, lib/glific/mails/new_partner_onboarded_mail.ex, priv/repo/migrations/20230725091730_addteamemailsto.exs
Target issue is #2941 
- Ran migration to add field `team_emails` in the organization table
- Fetch the JSON content from there and use it to send email
=> Issue support for adding emails

lib/glific/third_party/bigquery/bigquery_worker.ex, priv/repo/migrations/20230820104852_make_last_updated_at_non_nullable_in_bigquery_jobs.exs
To fix the last_updated_at column when the value is null. 
1. First we haveto run this query in the DB.
```
UPDATE bigquery_jobs
SET last_updated_at = '2023-08-10'
WHERE last_updated_at IS NULL;
```
2. Created a migration to make last_updated_at not nullable
3. Updated bigquery worker file to send the last_updated_at also on the creation time
=> bigquery_jobs  bug

lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific_web/registration_controller_test.exs
Target issues are #3180
#3177
sending the proper message for forgot password if the user is not registered or the user account does not exist and sending message when user is creating an account and that user already exists into the database
=> fix/Login:handle error message in forgot password

lib/glific/providers/balance_worker.ex, lib/glific/tickets.ex, lib/glific/tickets/ticket.ex, priv/repo/migrations/20231122115923_add_message_number_colum_in_ticket_table.exs, test/glific/tickets_test.exs, test/glific_web/schema/ticket_test.exs, test/support/fixtures/tickets_fixtures.ex
Target issue is #3125
get the previous message_number before creating the ticketing so that we can navigate to the exact location where the ticket was being created.
=> Ticketing System: Adding message number to tickets

lib/glific/clients/kef.ex, lib/glific_web/flows/flow_editor_controller.ex
Target issue is https://github.com/glific/glific-frontend/issues/2633
To check if the template type is media we need to get the type of the template from the API. Added the type in the response for the API
=> Added type in templates API for floweditor

lib/glific/flows/translate/export.ex, lib/glific/flows/translate/open_ai.ex
Added concurrency at language level, setting max concurrency at 2 as average number of language per org is 3
=> Auto Translate: Parallel Translation at lang level

lib/glific/providers/gupshup/partner/partner_api.ex, test/glific/partners/partners_test.exs
Target issue is #3214 
New feature has been added in partner api to set the callback url using api calls.
Takes 2 parameters:
1. Org_id
2. Callback Url
=> Partner API: Setting Callback URL

lib/glific_web/templates/live/stats_live.html.heex
Target issue is #3347 
- Added `word-break: break-all` to the broadcast table UI
=> Dashboard UI: added textwrap in the broadcast table

lib/glific/reports.ex
Target issue is #3238   
- Created a new function `remove_default_contacts` which gives a query to remove the simulator contacts by checking the prefix of contacts and Main Org account contact by checking `contact_id`
=>  Internal Dashboard: Filtering out default contacts from stats

assets/gql/contact_wa_groups/count_wa_contacts.gql, lib/glific/groups/contact_wa_groups.ex, lib/glific_web/resolvers/wa_group.ex, lib/glific_web/schema/contact_wa_group_types.ex, test/glific_web/schema/contact_wa_group_test.exs
Target issue is #3413
created the count api to get the count of contacts associated to the whatsapp groups
=> WA groups: count API to get the count of wa group contacts

lib/glific/partners.ex, test/glific/gcs_worker_test.exs
Target issue is #3491 
Actual handling of account not found is handled already with creating notification and deleting GCS. But due to a wrong interpolation of error in logs, interpolation error occurred instead.
Steps to reproduce this in tests,
- change the log level to :info and comment the purging like below in `config/test.exs`
```
config :logger,
level: :info,
```
- Remove the `inspect` which we added in the commit
- run ` mix test_full test/glific/gcs_worker_test.exs`
=> GCS Worker: Handling account not found error

priv/repo/seeds/20200723172939_add_glific_data.exs, test/glific/groups/whatsapp_group_test.exs
Replacing `Mix.env()` with `Application.get_env(:glific, :environment)` since the former doesn't work in gigalixir environment
=> Fetching right env in staging and prod

lib/glific/mails/notification_mail.ex
Target issue is #3618 
We were sending `team` as "" and no `send_to` which makes clause at ln: 107 execute and returns nil, resulting in `to` of sender to be `[]`
=> Notification mails: Using org name and email as `to` email address instead of empty list 

lib/glific/templates/interactive_templates.ex, lib/glific_web/resolvers/interactives.ex, lib/glific_web/schema/interactive_template_types.ex, test/glific/interactive_templates_test.exs
Target issue is #3641 
When translating an interactive template, it often happens that the character limit is fulfilled in english but the character limit exceeds in its hindi or other language translations. We need to show a warning message when saving the interactive language if any of the translations exceed the character limit.
=> Interactive Template: Add warning message for character limit exceedance

lib/glific/third_party/sheets/sheets.ex, test/support/fixtures.ex
Target issue is #3665   
https://docs.google.com/spreadsheets/d/17DKns-o7-NxkhYPMle-xNz9Z_iQ_9vCS2gvbNrYctu8/export?format=csv&&gid=0gid=0
https://docs.google.com/spreadsheets/d/17DKns-o7-NxkhYPMle-xNz9Z_iQ_9vCS2gvbNrYctu8/export?format=csv&gid=0
=> Google sheets: fixed wrong csv export url

lib/glific/third_party/sheets/api_client.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/resolvers/interactives.ex
Target issue is #3669 
This will increase the max escape line for flow translation import, interactive message translation import and google sheet csv download
=> Csv import: Increased max escape lines to 50

lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/providers/gupshup/template.ex, test/glific/mail_logs_test.exs, test/glific/partners/partners_test.exs, test/glific/templates_test.exs
Target issue is #3637
Currently, users do not receive helpful error messages when submitting HSM templates. There is one static message shown for all errors thus the user is not able to adjust their input correctly. This pull request solves that problem by showing the user what the actual error is. 
=> Improve the error message that users see upon hsm template submission 

config/dev.exs, lib/glific/flows/action.ex, lib/glific/flows/webhook.ex, test/glific/flows/action_test.exs
Target issue is #3742  
Due to the issue mentioned [here](https://github.com/glific/glific/pull/2690), the solution was to prevent webhooks with same context_id and url to run at same time. But due to this restriction same webhook nodes in a flow will not run
But the solution proposed in this PR is that to not run the webhook node if there is message in message_stream
=> Webhook: Preventing webhook node execution if there is message stream

lib/glific/clients/common_webhook.ex, test/glific/flows/common_webhook_test.exs
Target issue is #3813 
- Removed ward from results variable
- Using `administrative_area_level_3` for district variable
=> Geolocation: Changes in the results variable

lib/glific/jobs/user_jobs.ex
Reverts glific/glific#3846
We don't have to `skip_organization_id` for this, since the worker function is called for each org, and also set org_id in the process.
The only time this didn't work was for org_id `153`.
=> Revert "Contact Import: fetching pending user_jobs by skipping org id"

lib/glific_web/flows/flow_editor_controller.ex
Target issue is https://github.com/glific/glific-frontend/issues/3113
Added translations for the templates in the `/interactive-templates` api
=> Added translations for interactive templates

lib/glific_web/flows/flow_editor_controller.ex
Removed translations from the list api because it was taking a lot of time to load.
=> Removed translations from list interactive templates api

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
Target issue is #3989  
Stopping syncing `recent_messages` to `flow_counts` table and updating schema as well
=> BQ: Removing recent messages from Flow Counts

lib/glific/providers/maytapi/wa_worker.ex, test/glific/groups/whatsapp_message_test.exs
Related issue is https://github.com/glific/glific/issues/4059
Related error
```elixir
** (ErlangError) Erlang error: "%MatchError{term: {:error, #Ecto.Changeset<action: :update, changes: %{status: :sent, errors: %{message: \"{\\\"message\\\": \\\"BSP credentials does not exist\\\"}\"}, flow: :outbound, bsp_status: :error}, errors: [sender_id: {\"can't be blank\", [validation: :required]}, receiver_id: {\"can't be blank\", [validation: :required]}], data: #Glific.Messages.Message<>, valid?: false, ...>}}"
```
https://appsignal.com/project-tech4dev/sites/602fcb580264444badac30d8/exceptions/incidents/82/samples/timestamp/2025-03-19T06:25:00Z
=> WA Messages: Checking maytapi provider is active instead of Gupshup

lib/glific/third_party/bigquery/bigquery.ex, lib/glific_web/providers/maytapi/controller/message_event_controller.ex, test/glific/bigquery_test.exs, test/glific_web/schema/wa_reaction_test.exs
Target issue is #3997  
- Parsing `Date.t()` also now so that org which has contact_field inserted date in `Date` format rather than `DateTime.t` can also sync their contacts to BQ
=> Bigquery: Handling date-only format in the formatter

lib/glific/profiles.ex, priv/repo/migrations/20250711055838_add_index_contact_groups.exs, test/glific/profiles_test.exs
Reverts glific/glific#4284
Reverting this since this PR is dependent on FE PR as mentioned https://github.com/glific/glific/pull/4284#issuecomment-3079094364
=> Revert "Cascade Delete Contact When Deleting Default Profile"

.gigalixir/releases/includes.txt, .profile.d/001_fixup_apt.sh, .profile.d/002_ssh_profile_setup.sh
Target issue is #4327  
`.profile.d/001_fixup_apt.sh` file will make the custom installed apt libraries (like ffmpeg) available in runtime, by adding it to the paths.
`.profile.d/002_ssh_profile_setup.sh` -  does the auto-sourcing of above file.
`.gigalixir/releases/includes.txt` - Makes sure the first file is included while building the artifact.
=> Added scripts that will make ffmpeg available in runtime

lib/glific/messages.ex, lib/glific/providers/gupshup/template.ex, lib/glific/templates.ex, lib/glific/templates/session_templates.ex, lib/glific_web/schema/session_template_type.ex, priv/repo/migrations/20250716033709_add_footer_to_session_templates.exs, test/glific/templates_test.exs
Target issue is https://github.com/glific/glific/issues/4249
-  Gupshup supports an optional footer field in HSM templates for additional message context.
- Glific currently does not support the footer, limiting the ability to utilize this feature.
- Added footer column to the hsm_templates table as a nullable text field via migration.
- Updated GraphQL API to accept and return the optional footer field in create, update, and fetch operations.
- Maintained backward compatibility by making footer optional, ensuring existing templates continue to work unchanged.
=> Add footer to session template

lib/glific/contacts.ex, lib/glific/searches.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/seeds/seeds_migration.ex, lib/glific_web/providers/gupshup/controllers/message_controller.ex, test/glific_web/providers/maytapi/controllers/message_controller_test.exs, test/glific_web/schema/search_test.exs
Target issue is https://github.com/glific/glific/issues/4285 
Before deploying this PR, we need to update contact_type of the simulator contacts in prod and staging to WABA, currently they are null
=> Search: Only WABA contacts will be returned in the search api

lib/glific/flows/contact_action.ex, lib/glific/flows/flow_context.ex, priv/gettext/errors.pot, test/glific/flows/flow_context_test.exs
Target issue is https://github.com/glific/glific/issues/4324 
- Added `message_type` and `message_media` to recent_inbound and recent_outbound objects in flow_context.
- Check the distinctiveness of message by checking the outbound media attachments with `message_media` in flow_context instead of empty body.
- HSMs and interactive msgs require mandatory body, so we don't have to check for that.
=> Message: Proper handling of infinity loop for media only outbound session messages 

lib/glific/third_party/kaapi/api_client.ex, lib/glific/third_party/kaapi/migration.ex
- Update project_name to use shortcode instead of org_name.
- Remove user_name field from request body in both ApiClient and Migration
modules.
=> Remove sending username for onboarding to kaapi

lib/glific/erase.ex
When we delete message_broadcasts we need to update the messages tables message_broadcast_id to null, and its a foreign-key in messages table. Since the messages table has millions of rows, the delete query was timing out.  So further db purging and vacuuming was not working for a month, resulting in increased db size.
Instead now we delete message_broadcast_contacts table (which can have millions of rows if not cleared weekly) and message broadcasts table will not grow exponentially.
=> Purging messages_broadcast_contacts

lib/glific/third_party/gcs/gcs_worker.ex
GCS worker uses Bigquery worker to update the messages table on media url updation.
So missed this case. Added process state updation of repo replica in gcs worker too
=> GCS: Updating process state of replica in gcs worker
