lib/glific/contacts.ex, lib/glific/contacts/contact.ex, test/glific/contacts_test.exs
=> Migrate contact context

test/glific/partners_test.exs
=> Partners: test coverage

lib/glific/messages.ex, lib/glific/messages/message.ex, lib/glific/support/seeds.ex, lib/glific_web/schema/message_type.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, test/glific/messages_test.exs, test/glific_web/schema/message_test.exs, test/support/fixtures.ex
=> add contact_id field to messages and fix all api calls, tests etc

.github/workflows/continuous-integration.yml
- Trigger on merging the branch to master for coverage badge.
=> #Added new action to CI

config/config.exs, lib/glific/messages/message.ex, lib/glific/support/seeds_scale.ex, mix.exs, priv/repo/migrations/20200601193405_create_glific_tables.exs, priv/repo/migrations/20200615073630_add_parent_id_to_messages.exs, test/glific/messages_test.exs
#106 
- Added Procedure for parent
- Added Procedure or ancestors
- Test case for parent
- Test Case for ancestors
=> Parent and ancestors  for messages 

config/config.exs, lib/glific/communications/message.ex, lib/glific/conversations.ex, priv/repo/migrations/20200615073630_add_parent_id_to_messages.exs
=> Update conversation API based on the message ancestors

config/config.exs, lib/glific/communications/message.ex, lib/glific/messages/message.ex, lib/glific_web/providers/gupshup/controllers/message_event_controller.ex, lib/glific_web/providers/gupshup/router.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, test/glific/communications_test.exs, test/glific_web/providers/gupshup/controllers/message_event_controller.exs
=> Message Communication workflow cleanups

TODO.md, lib/glific/taggers/keyword.ex, lib/glific/tags.ex, test/glific/tags_test.exs
=> Tag Keywords mapping

assets/gql/conversations/by_contact_id.gql, assets/gql/conversations/list.gql, lib/glific/conversations.ex, lib/glific_web/resolvers/conversations.ex, lib/glific_web/schema/conversation_types.ex, test/glific_web/schema/conversation_test.exs
1. Added function in context.
2. Added graphql query: get by id with filters
3. Added basic test case
=> Feature: Get single conversation by id

test/glific/glific_test.exs
=> add user names and roles and tests

priv/repo/migrations/20200605170830_search_messages.exs
- Remove the partition view and replaced rank with message_number
=> Modify search function as per the conversation API changes 

lib/glific/contacts.ex, test/glific/contacts_test.exs
There was an issue with the contact upsert method. 
If there is a conflict it just updates the phone and skips other fields.
=> User Opt out bug fix

assets/gql/searches/search.gql, lib/glific/searches.ex, lib/glific_web/resolvers/searches.ex, lib/glific_web/schema/search_type.ex, test/glific_web/schema/search_test.exs
=> (#162) save search options

api.docs/includes/_search.md, assets/gql/searches/search.gql, lib/glific/searches.ex, lib/glific_web/schema/search_type.ex, test/glific_web/schema/search_test.exs
- Renamed searchLable to saveSearchLabel
- Updated Doc
=> renamed Saved Search

api.docs/includes/_session_templates.md, assets/gql/session_templates/list.gql, lib/glific/templates.ex, lib/glific_web/schema/session_template_type.ex, test/glific/templates_test.exs, test/glific_web/schema/session_template_test.exs
=> Session template offset

README.md
- Added Open Issues Github Badge.
=> More github badges

api.docs/includes/_contacts.md, assets/gql/contacts/contact_location.gql, lib/glific/communications/message.ex, lib/glific/contacts.ex, lib/glific/contacts/location.ex, lib/glific/messages/message.ex, lib/glific/providers/gupshup/message.ex, lib/glific/providers/message_behaviour.ex, lib/glific_web/providers/gupshup/controllers/message_controller.ex, lib/glific_web/providers/gupshup/router.ex, lib/glific_web/resolvers/contacts.ex, lib/glific_web/schema/contact_types.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, test/glific_web/providers/gupshup/controllers/message_controller_test.exs, test/glific_web/schema/contact_test.exs
1. Contact's location: migration, schema, context create function
2. Inbound location message: controller, context and tests
3. Graphql API to get contact's location, tests and doc
=> Feature: contact's location

lib/glific_web/resolvers/messages.ex, lib/glific_web/schema/message_types.ex
=> Manual Subscription was not working

api.docs/includes/_auth.md
=> Changes in auth docs after OTP

api.docs/includes/_messages.md, lib/glific/communications/message.ex, lib/glific/messages.ex, lib/glific/providers/gupshup/message.ex, lib/glific/providers/message_behaviour.ex, lib/glific_web/schema/message_types.ex, test/glific/communications_test.exs
1. Added send_at param to send a message at a scheduled time
2. Job update defaults to now
3. Test and doc update
=> Feature: message send at specific time

lib/glific/contacts.ex, lib/glific/groups.ex, lib/glific/messages.ex, lib/glific/partners.ex, lib/glific/repo.ex, lib/glific/tags.ex, lib/glific/templates.ex, lib/glific/users.ex
1. Fixed error for opts_with order by field
2. WIP
=> Code cleanup

api.docs/includes/_auth.md, lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific_web/registration_controller_test.exs
Removing password_confirmation from API
Adding it to params for pow plug
Test and doc update
=> Removing password_confirmation from API

.gitignore, api.docs/includes/_auth.md, lib/glific/application.ex, lib/glific_web/api_auth_plug.ex, lib/glific_web/controllers/api/v1/registration_controller.ex, lib/glific_web/controllers/api/v1/session_controller.ex, mix.exs, test/glific_web/registration_controller_test.exs, test/glific_web/session_controller_test.exs
1. Setting expiry time for excess token.
2. Using mnesia for storing session data.
=> Feature: session token

lib/glific/communications/message.ex, lib/glific/tags.ex, test/glific/communications_test.exs
=> Remove unread tag for automated messages

config/config.exs
=> Glifix proxy

api.docs/includes/_messages.md, api.docs/includes/_search.md, assets/gql/searches/search.gql, lib/glific/communications/message.ex, lib/glific/messages.ex, lib/glific/messages/message.ex, lib/glific/processor/consumer_tagger.ex, lib/glific/providers/gupshup/message.ex, lib/glific/providers/message_behaviour.ex, lib/glific/taggers/tagger_helper.ex, lib/glific_web/schema/message_types.ex, mix.exs, priv/repo/migrations/20200601193405_create_glific_tables.exs, priv/repo/seeds_prod.exs, test/glific/communications_test.exs, test/glific_web/schema/search_test.exs
1. Tagger helper for tagging inbound and outbound messages
Now it will tag messages before publishing the subscription for messages.
2. For scheduled message: send_at field in the message table
3. Updated saved search seed and tests
=> Feature Improve tagging

api.docs/includes/_contacts.md, api.docs/includes/_users.md, lib/glific/contacts/contact.ex, lib/glific/users/user.ex, lib/glific_web/schema/contact_types.ex, lib/glific_web/schema/users_types.ex
1. Added users groups in graphql query
2. Added contacts groups in graphql query
=> Improve users and contacts query with groups field

lib/glific_web/controllers/api/v1/registration_controller.ex
=> Restructure API response

api.docs/includes/_auth.md, lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific_web/registration_controller_test.exs
1. Respond with session tokens in reset-password API which can be used for login
2. Cleanup using alias in registration controller
=> Improve forgot password: respond with session tokens for login

lib/glific/flows/message_vars_parser.ex, test/glific/flows/message_vars_parser_test.exs
- Added test cases for Message variable parser
- Added support for more variable types
=> Expand Results with Massage vars

api.docs/includes/_contacts.md, api.docs/includes/_flows.md, api.docs/includes/_groups.md, api.docs/includes/_languages.md, api.docs/includes/_messages_media.md, api.docs/includes/_organizations.md, api.docs/includes/_providers.md, api.docs/includes/_saved_searches.md, api.docs/includes/_session_templates.md, api.docs/includes/_users.md, lib/glific/flows/contact_setting.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/settings.ex, lib/glific/users.ex, lib/glific_web/schema/language_types.ex, lib/glific_web/schema/organization_types.ex, lib/glific_web/schema/provider_types.ex, test/glific/flows/action_test.exs, test/glific/flows/contact_setting_test.exs, test/glific/flows/node_test.exs, test/glific/settings_test.exs
1. Updated docs
2. Included opts in organizations, providers and languages query
=> Feature lists filters update

config/dev.secret.exs.txt, lib/glific/seeds/seeds_dev.ex, priv/repo/seeds/20200723172939_add_glific_data.exs
1. Added API call to prod seed, to update the contacts table with already opted-in contacts.
2. To call this API, the developer needs to add Gupshup API URL in dev.secret.exs, with Gupshup app name.
=> Feature: Integrate Gupshup Opt-In API using seed

lib/glific/flows.ex, lib/glific/seeds/seeds_dev.ex, test/glific_web/schema/contact_test.exs
Added seed message for each contact
=> Seed message for each contact

lib/glific/seeds/seeds_dev.ex
Don't seed test templates in the development environment
=> Don't seed test templates in development environment

api.docs/includes/_users.md, assets/gql/users/fields.frag.gql, assets/gql/users/update.gql, assets/gql/users/update_current.gql, lib/glific/flows/contact_action.ex, lib/glific/groups.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/users.ex, lib/glific/users/user.ex, lib/glific_web/resolvers/users.ex, lib/glific_web/schema/users_types.ex, test/glific/groups_test.exs, test/glific/users_test.exs, test/glific_web/schema/user_test.exs, test/support/fixtures.ex
1. Update current user API
2. Update user API which also updates user groups
3. Changeset for user updates
4. Updated roles list to none, staff, manager, admin
=> Feature update user

api.docs/includes/_users.md, lib/glific/users/user.ex, lib/glific_web/schema/users_types.ex
Added a graphql query to get list of roles
=> Roles list API

lib/glific/flows/contact_action.ex, lib/glific/messages/message.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, priv/repo/migrations/202008121280621_alter_messages_table_with_uuid.exs, test/glific/flows/node_test.exs
1. Added migration file to alter messages table with a new field UUID, keeping it nullable.
2. Setting flow's action UUID as message UUID
=> Feature message UUID

api.docs/includes/_users.md, assets/gql/users/list_roles.gql, assets/gql/users/update.gql, lib/glific/users/user.ex, lib/glific_web/resolvers/users.ex, lib/glific_web/schema/users_types.ex, test/glific_web/schema/user_test.exs
1. roles API  response structure update
2. update_user API input structure update
3. test and docs update
=> Users APIs input and response structure update

assets/package-lock.json, assets/package.json
=> Revert "old dependency"

api.docs/includes/_contacts.md, assets/gql/contacts/search.gql, lib/glific/contacts.ex, lib/glific_web/resolvers/contacts.ex, lib/glific_web/schema/contact_types.ex, test/glific_web/schema/contact_test.exs, test/support/fixtures.ex
1. Get contacts only within groups list
2. Get contacts only with tags list
=> Feature search contacts API

api.docs/includes/_contacts.md, lib/glific/contacts.ex, test/glific_web/schema/contact_test.exs
Fix for a filter with multiple groups responds with multiple instances of same contact
=> Contact search cleanup for filter with multiple groups

lib/glific/flows.ex, lib/glific/flows/flow.ex, test/glific/flows_test.exs
1. Load flow revision with status "done"
2. Update cached flow definition with publish flow,
3. Test updates
=> Flow revision status updates

Dockerfile, config/releases.exs
- Added dependency for the AppSignal for Elixir package.
- Added configurable API key for AppSignal.
=> AppSignal compatibility for docker env

api.docs/includes/_flows.md, assets/gql/flows/contact_flow.gql, assets/gql/flows/group_flow.gql, lib/glific/flows.ex, lib/glific/seeds/seeds_dev.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific_web/schema/flow_test.exs
1. Start flow for contact API
2. Start flow for contacts of a group API
=> Feature: Start flow APIs

api.docs/includes/_search.md, lib/glific_web/schema/search_type.ex
1. Added graphql schema and doc
=> Seach conversations filter: include user

api.docs/includes/_users.md, lib/glific_web/resolvers/users.ex, lib/glific_web/schema/users_types.ex, test/glific_web/schema/user_test.exs
Making groupIds non-mandatory field
=> Feature: updateUser API changes

api.docs/includes/_contact_tag.md, api.docs/includes/_messages_tags.md, assets/gql/contact_tags/update.gql, lib/glific/communications.ex, lib/glific/tags.ex, lib/glific/tags/contact_tag.ex, lib/glific/tags/contact_tags.ex, lib/glific_web/resolvers/tags.ex, lib/glific_web/schema/contact_tag_types.ex, test/glific/tags_test.exs, test/glific_web/schema/contact_tag_test.exs, test/glific_web/schema/contact_tags_test.exs
=> Feature: update contact tags

api.docs/includes/_users.md, assets/gql/users/update_current.gql, lib/glific_web/resolvers/users.ex, lib/glific_web/schema/users_types.ex, test/glific_web/schema/user_test.exs, test/support/fixtures.ex
Update current user mutation fix: getting current user id from the context
=> update current user fix

assets/gql/users/current.gql, lib/glific/partners/out_of_office.ex, lib/glific/templates.ex, test/glific_web/schema/user_test.exs
1. Disabled days type fix
2. Query naming convention fix
3. Current user graphql mutation test
=> Cleanup and fixes

api.docs/includes/_organizations.md, assets/gql/organizations/fields.frag.gql, lib/glific/flags.ex, lib/glific/partners/organization.ex, lib/glific_web/schema/organization_types.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, test/glific_web/schema/organization_test.exs
1. Organization's timezone migration, schema, doc update
2. Getting organization's timezone from DB for out of office flow
=> Feature: organization timezone

api.docs/includes/_organizations.md, assets/gql/organizations/list_timezones.gql, lib/glific/flags.ex, lib/glific/partners.ex, lib/glific/partners/organization.ex, lib/glific_web/schema/organization_types.ex, test/glific_web/schema/organization_test.exs
1. Validation for timezone using tzdata list
2. Flags and organization cleanup for timezone
3. Graphql API query to get list of timezones
4. Tests and docs updates
=> Feature: timezone cleanup

README.md, buildspec.yml.sample
- Added buildspec sample file that includes the instructions of creating a new docker image and deploying to AWS ECR.
=> Build guidelines for ECS

lib/glific/communications/message.ex, lib/glific/contacts.ex, lib/glific/flags.ex, lib/glific/flows/periodic.ex, lib/glific/messages.ex, lib/glific/partners.ex, lib/glific_web/flows/flow_editor_controller.ex, test/glific/contacts_test.exs, test/glific/flags_test.exs, test/glific/flows/periodic_test.exs, test/glific/partners_test.exs, test/glific_web/schema/message_test.exs, test/glific_web/schema/search_test.exs
1. Using organization id from attrs or conn
2. Temporary fix for organization id in periodic test
3. Temporary fix for organization id in flags
=> Feature organization id cleanup

api.docs/includes/_flows.md, api.docs/includes/_scalars.md, api.docs/index.html.md, assets/gql/flows/publish.gql, lib/glific/partners/organization.ex, lib/glific/partners/out_of_office.ex, lib/glific_web/flows/flow_editor_controller.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific/flags_test.exs, test/glific_web/flows/flow_editor_controller_test.exs, test/glific_web/schema/flow_test.exs
1. List organization's language for flows
2. Publish flow by UUID
=> Flow updates: publish flow and languages

lib/glific/enums/constants/enums.ex, lib/glific_web/schema/middleware/authorize.ex, lib/glific_web/schema/provider_types.ex, test/glific_web/schema/provider_test.exs, test/glific_web/schema/search_test.exs, test/support/conn_case.ex
1. Added glific_admin role
2. For providers create and update APIs using the glific_admin role for authorization
=> Feature: glific_admin role

api.docs/includes/_contact_group.md, api.docs/includes/_contact_tag.md, api.docs/includes/_messages_tags.md, api.docs/includes/_user_group.md, assets/gql/contact_groups/delete.gql, assets/gql/contact_tag/delete.gql, assets/gql/message_tag/delete.gql, assets/gql/user_groups/delete.gql, lib/glific/groups.ex, lib/glific/tags.ex, lib/glific_web/resolvers/groups.ex, lib/glific_web/resolvers/tags.ex, lib/glific_web/schema/contact_group_types.ex, lib/glific_web/schema/contact_tag_types.ex, lib/glific_web/schema/message_tag_types.ex, lib/glific_web/schema/user_group_types.ex, test/glific/groups_test.exs, test/glific/tags_test.exs, test/glific_web/schema/contact_group_test.exs, test/glific_web/schema/contact_tag_test.exs, test/glific_web/schema/message_tag_test.exs, test/glific_web/schema/user_group_test.exs
1. Removed APIs for delete a relationship row by id
2. We need to add a check for a relationship update. Added comments for that.
=> Organization check cleanup

lib/glific/communications/message.ex, lib/glific/contacts.ex, test/glific/contacts_test.exs
=> contact status

lib/glific/bigquery.ex, lib/glific/bigquery/bigquery_schema.ex, lib/glific/partners.ex
=> Setup bigquery schema

lib/glific/messages.ex, priv/repo/seeds/20201013014353_v0_5_1_alter_glific_data.exs
1. Fix for session_uuid of contacts added to multiple organizations.
2. Fix for seeding tags to already added organization
=> Fix for multiple organizations

lib/glific/bigquery.ex, lib/glific/bigquery/bigquery_schema.ex, lib/glific/partners.ex
1. Create a view for contacts and messages join table using bigquery API
2. Alter bigquery schema function
=> Feature: bigquery alter schema, create view

api.docs/includes/_flows.md, assets/gql/flows/copy.gql, lib/glific/flows.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific/flows_test.exs, test/glific_web/schema/flow_test.exs
API to make a copy of a flow with the latest flow revision
=> Copy a flow feature

lib/glific/bigquery.ex, lib/glific/partners.ex
=> Bigqurey credential update fix

CHANGELOG.md
- Updated changelog order and added some frontend changes.
- Reordered the changelog content
=> Updated changelog - frontend

priv/repo/migrations/20201207123324_v0_8_2_alter_glific_tables.exs
1. index to improve the time of flow activity API
2. index to improve search query for all in the chat page
=> Improve queries using index

lib/glific/communications/message.ex, lib/glific_web/schema/message_types.ex
=> Revert "Feature/message status subscription"

lib/glific/templates.ex
=> Revert "Added logging for the session template issues"

lib/glific/seeds/seeds_scale.ex
Changes to be made to create_results_entry function
=> Adding seeder functions for flow_results

lib/glific/flows/flow_context.ex, lib/glific/jobs/bigquery/bigquery_worker.ex
=> Appsignal error (#916)

lib/glific/jobs/bigquery/bigquery_worker.ex, priv/repo/migrations/20210121071908_v0_9_5_alter_update_contact_updated_at_trigger.exs
=> added trigger to update contact updated_at

lib/glific/bigquery.ex, lib/glific/bigquery/bigquery_schema.ex
=> biqquery changes

lib/glific/bigquery.ex, lib/glific/bigquery/bigquery_schema.ex, lib/glific/jobs/bigquery/bigquery_worker.ex, mix.exs
=> Message changes

config/config.exs, lib/glific/jobs/bigquery/bigquery_worker.ex, lib/glific/jobs/gcs/gcs_worker.ex
=> removed queues

config/config.exs, lib/glific/gcs.ex, lib/glific/partners.ex, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs, test/glific/partners_test.exs
- Moved waffle token fetcher in the GCS
=> Refectoring:  GCS 

lib/glific/communications/message.ex
Seems like we should ensure poolboy also has a timeout in case our friends at genserver ignore the timeout
=> add timeout to poolboy also

lib/glific/communications/message.ex
For now, while we are debugging, lets kill the consumer worker process
=> kill runaway consumer worker

lib/glific/messages.ex, priv/repo/migrations/20210205192848_add_status_to_messages.exs, test/glific/messages_test.exs
=> Test cases updates

CHANGELOG.md, config/dev.exs, config/releases.exs, config/releases.exs.txt, config/test.exs, lib/glific/appsignal.ex, lib/glific/flows/contact_action.ex, lib/glific/flows/router.ex, mix.exs
continuing our struggle with tracking down our spike culprit, but at the same time improving our code base
=> lets turn on ecto repo logging to try and catch the spike

lib/glific.ex, lib/glific/communications.ex, lib/glific/flows/contact_action.ex, lib/glific/flows/webhook.ex, lib/glific/jobs/gcs/gcs_worker.ex, lib/glific/repo.ex, lib/glific/searches.ex, lib/glific/templates.ex, lib/glific_web/schema/generic_types.ex
- A generic function to handle all the string to atom conversions.
- Send those errors to app signals with the stack trace.
=> Appsignal errors

lib/glific/providers/gupshup/api_client.ex, lib/glific/providers/gupshup/contacts.ex
=> updating last communication at

lib/glific/flows/flow_context.ex, lib/glific/processor/consumer_flow.ex
=> fix checks

lib/glific_web/schema/search_type.ex
=> changing authorize to staff

priv/repo/migrations/20210218084225_update_all_saved_search_args.exs, priv/repo/seeds/20200723172939_add_glific_data.exs
Change the arguments for the  saved search with 'All' shortcode
=> fixed all saved search

lib/glific/bigquery/bigquery_schema.ex, lib/glific/seeds/seeds_scale.ex, priv/repo/migrations/20200601193405_create_glific_tables.exs, priv/repo/migrations/20200924193405_v0_4_1_alter_glific_tables.exs, priv/repo/migrations/20201013101431_v0_5_1_alter_glific_tables.exs, priv/repo/migrations/20201023101018_create_flow_label_table.exs, priv/repo/migrations/20201027171943_v0_5_2_alter_glific_tables.exs, priv/repo/migrations/20201101121212_v0_6_0_alter_glific_tables.exs, priv/repo/migrations/20201214124257_v0_8_4_alter_glific_tables.exs, priv/repo/migrations/20201222120543_v0_8_7_alter_glific_tables.exs, priv/repo/migrations/20210106110739_v0_9_2_alter_glific_tables.exs, priv/repo/migrations/20210114100139_v0_9_4_alter_glific_tables.exs, priv/repo/migrations/20210122141223_create_trigger_table.exs, priv/repo/migrations/20210205192848_add_status_to_messages.exs
Flow result modifications include : Generating flow_id's for joining with messages table, adding a constant time value to updated_at to simulate user session times and adding to the flow_results json objects
=> Adding comments to contacts and messages tables & modifications to flow result seeding

priv/repo/seeds/20200723172939_add_glific_data.exs
=> Change contact limit

lib/glific/flows/exit.ex, lib/glific/flows/flow_count.ex, lib/glific/flows/node.ex
=> removing upsert

lib/glific/templates.ex, lib/glific_web/flows/flow_editor_controller.ex, test/glific_web/flows/flow_editor_controller_test.exs
- Adding filter to show only approved templates when sending templated in flow
=> adding filter for approved templated

lib/glific/searches/collection_count.ex
handle edge case of not needing to collect stats for any orgs
=> simulator contacts cannot be opted out

lib/glific/flows/action.ex
- Added support to send template to staff
=> Feature: added support for sending template to staff

lib/glific/flows/message_vars_parser.ex, test/glific/flows/message_vars_parser_test.exs
Added check for period placed at the end of variable like : Hello @contact.name.
=> added a check for trailing fullstop

lib/glific_web/flows/flow_editor_controller.ex, test/glific_web/flows/flow_editor_controller_test.exs
We are not allowing users to create a collection from the flows. 
In this PR I restrict them and convert UUID to 0
=> App signal error #1152

lib/glific/partners.ex, priv/repo/seeds/20210225052427_disable_chatbase.exs
- disabling active credentials for chatbase
- hiding chatbase as provider
=> disabling chatbase

lib/glific/bigquery/bigquery_schema.ex, lib/glific/contacts/contact.ex, lib/glific/jobs/bigquery/bigquery_worker.ex
Made changes to bigquery_worker, bigquery_schema and contact.ex to include user details within the BQ tables
=> Adding user details to the contact table

priv/repo/migrations/20210225083751_alter_data.exs, priv/repo/migrations/20210225083751_v0_11_6_alter_glific_tables.exs
- Updating contact  table to delete foreign key constraint on delete
=> Updating delete contact

lib/glific/bigquery/bigquery_schema.ex, lib/glific/contacts/contact.ex, lib/glific/jobs/bigquery/bigquery_worker.ex
=> Revert "Adding user details to the contact table"

lib/glific/flows/flow.ex, lib/glific/messages.ex, test/glific/flows/periodic_test.exs
=> Fix issue #1164

lib/glific/partners.ex, lib/glific_web/plugs/plug.ex, lib/glific_web/plugs/subdomain_plug.ex, lib/glific_web/tenants.ex, test/glific/partners_test.exs, test/glific_web/tenants_test.exs
=> clean up and tighten code base

lib/glific/messages.ex, test/glific/messages_test.exs
Added test cases for:
- validating nil and empty url
- validating  media size 
- media is valid
- validating header
=> Media validation

config/test.exs, lib/glific/processor/consumer_flow.ex, priv/data/flows/test.json, test/glific/flows/action_test.exs, test/glific/flows_test.exs, test/glific/processor/consumer_flow_test.exs, test/glific_web/tenants_test.exs, test/support/fixtures.ex
=> onwards and upwards towards our coverage goal

config/test.exs, lib/glific/contacts.ex, lib/glific/groups.ex, test/glific/flows/action_test.exs, test/glific/flows_test.exs, test/glific/processor/consumer_flow_test.exs
=> fix bug with permissioning, also fix leftover formatting issues

coveralls.json, lib/glific/bigquery.ex, lib/glific/jobs/bigquery/bigquery_worker.ex, lib/glific/seeds/seeds_dev.ex, test/glific/bigquery_test.exs
added test cases for:
- queuing messages table
- queuing messages_delta table
- queuing contacts table
- queuing contacts_delta table
- queuing flows table
- queuing flows_results table
- format_date in bigquery
- seeder for flow results in seed_dev
- format update fields
=> adding bigquery test cases

lib/glific/flows/action.ex, lib/glific/seeds/seeds_dev.ex, test/glific/contacts_test.exs, test/glific/flows/flow_context_test.exs
=> fix appsignal error, #1197

build_scripts/remote_console.sh, build_scripts/ssh_profile.sh, build_scripts/staging_build.sh, staging_build.sh
Write a script that will make the build on staging for a given tag.
Steps: 
Move to the project directory and run the following command
```
./build_scripts/staging_build.sh v0.11.x
```
Pending items: 
Automate the migration and seeder.
=> build script

config/prod.exs, lib/glific/clients.ex, lib/glific/clients/tap.ex, lib/glific/clients/weunlearn.ex, lib/glific/flows/contact_action.ex, test/glific/clients_test.exs, test/support/fixtures.ex
=> making the staff id a pluggable parameter

assets/package-lock.json, lib/glific/contacts.ex, lib/glific/contacts/import.ex, lib/glific/providers/gupshup/contacts.ex, test/glific/contacts_test.exs
The purpose of this code change is to add an API to the Contact module, to import contacts for an organization, and add them to a group. The contacts would be added via a csv file, whose format can be:
```
name,phone,opt_in,language
Madhav,6476850947,2020-08-11,English
Avneet1, 4379713477,2020-08-01,Hindi
```
The method has the signature: `import_contacts(file_path, organization_id, group_id) ` and is part of `Glific.Contacts.Import` module. The method right now can only be invoked via the shell.
TBD
=> Add Import Contacts API

lib/glific/flows/flow_context.ex, lib/glific/searches.ex
* fix #1239
* merge flow chenages
* merge changes into master
Co-authored-by: Donald A. Lobo <donald.lobo@gmail.com>
=> Patch/v1.0.3 (#1260)

lib/glific/contacts.ex, mix.exs, test/glific/messages_test.exs
=> merging this to 1.0

lib/glific/clients.ex, lib/glific/clients/reap_benefit.ex, lib/glific/clients/stir.ex, lib/glific/clients/tap.ex, lib/glific/contacts.ex, lib/glific/jobs/gcs/gcs_worker.ex, test/glific/clients_test.exs
=> get clients interface ready for v1.2

lib/glific/jobs/bigquery/bigquery_worker.ex
- We were missing the updated column on the messages and flow results. 
- That's where we were getting those errros.
=> Big query bug fixes

api.docs/includes/_saved_searches.md, lib/glific/searches.ex, lib/glific_web/schema/search_type.ex, test/glific/searches_test.exs
- Added filter with is_reserved
- Added test case for listing saved searches based on is_reserved filter
- Updating docs
=> Saved search filter

lib/glific/contacts.ex
=> resolve conflicts

lib/glific/contacts.ex, lib/glific/contacts/import.ex, lib/glific/groups.ex, lib/glific/providers/gupshup/contacts.ex, test/glific/contacts_test.exs, test/support/fixture.csv
Made the following improvements to `Glific.Contacts.Import.import_contacts`:
1. Create a group if it does exist.
2. Delete contacts.
3. Conditional opt_in
=> Import Contact code improvements

lib/glific/application.ex, lib/glific/flows/broadcast.ex, lib/glific/providers/gupshup/api_client.ex, lib/glific/seeds/seeds_scale.ex, test/glific_web/schema/trigger_test.exs
=> get checks to pass

README.md
=> Added cypress badge in readme

lib/glific/contacts/contact.ex, lib/glific/searches/collection_count.ex, priv/repo/migrations/20210316195915_message_number_status.exs, test/glific/messages_test.exs
=> lets start numbering messages from 1

.gitignore, lib/glific/messages/message.ex, lib/glific/seeds/seeds_migration.ex, priv/repo/migrations/20210315183726_update_message_number.exs, test/support/fixture.csv
=> use before trigger

lib/glific/clients.ex, lib/glific/clients/reap_benefit.ex, lib/glific/clients/tap.ex, lib/glific/gcs.ex, lib/glific/jobs/gcs/gcs_worker.ex, lib/glific/partners.ex, lib/glific_web/uploaders/media.ex, mix.exs, test/glific/clients_test.exs
=> fix GCS scope parameter

lib/glific/messages.ex, lib/glific/searches.ex, lib/glific/searches/full.ex
=> Search contact limit

lib/glific/searches.ex
=> simplify search query

api.docs/includes/_import.md, assets/gql/contacts/ImportFields.frag.gql, assets/gql/contacts/import.gql, lib/glific/contacts/import.ex, lib/glific_web/resolvers/contacts.ex, lib/glific_web/schema/contact_types.ex, test/glific/contacts_test.exs, test/glific_web/schema/contact_test.exs
Add the Import API for the `Contacts.Contact.Import` module
=> Add import API + tests

lib/glific/jobs/gcs/gcs_worker.ex
- disabling GCS when billing is not enabled
- updating notification when billing is disabled and disabling GCS
=> Disabling GCS when billing is not enabled

lib/glific/bigquery.ex
=> Create notification when account is disabled.

CHANGELOG.md, lib/glific/bigquery.ex, lib/glific/jobs/gcs/gcs_worker.ex, lib/glific/jobs/minute_worker.ex, lib/glific/seeds/seeds_stats.ex, lib/glific/stats.ex
=> clean up stats code and mkigrattions

CHANGELOG.md
=> Updated frontend change log for v1.3

lib/glific/communications/message.ex, lib/glific/contacts.ex, test/glific/messages_test.exs
=> Specific error messages

lib/glific/flows/action.ex
=> tweak changes to setting language

lib/glific/flows/contact_setting.ex, test/glific/flows/contact_setting_test.exs
=> adding check for language for contact

lib/glific/bigquery/bigquery_schema.ex
Contact name should not be a required field.
=> Contact name should not be a required field. 

lib/glific/partners.ex, test/glific/partners_test.exs
Updating severity of error raised to critical on disabling credential
=> Goth token error level

lib/glific/clients.ex, lib/glific/clients/sol.ex, lib/glific/jobs/bigquery/bigquery_worker.ex, lib/glific/partners.ex, lib/glific/seeds/seeds_migration.ex, test/glific/clients_test.exs, test/glific/partners_test.exs
=> add GCS structure for SOL

priv/repo/migrations/20210406052407_v1_3_1_alter_glific_tables.exs, priv/repo/migrations/20210409045013_v1_4_0_alter_glific_tables.exs
=> Localization updates

.iex.exs, config/test.exs, lib/glific/flows.ex, lib/glific/flows/exit.ex, lib/glific/flows/flow.ex, lib/glific/flows/flow_context.ex, lib/glific/flows/node.ex, lib/glific/flows/router.ex, priv/data/flows/test.json, priv/repo/migrations/20210406052407_v1_3_1_alter_glific_tables.exs, priv/repo/migrations/20210409045013_v1_4_0_alter_glific_tables.exs, test/glific/flows_test.exs, test/glific/users_test.exs
Lets have default behavior for no response and other links, helps makes things easier for NGOs building flows
=> steps towards making it easier for no response and other

lib/glific/flows/flow_context.ex, lib/glific/flows/router.ex, lib/glific/flows/webhook.ex, lib/glific_web/router.ex, test/glific/flows/flow_context_test.exs
=> clean up results code

config/releases.exs, config/releases.exs.txt
Add stripe config to release.exs configuration.
=> Add stripe config to release

lib/glific/flows/node.ex, test/glific/flows/node_test.exs
=> lets get the new format of wait_for_time handled

lib/glific/stats.ex
=> start moving global stats table to BQ as soon as they are published

lib/glific/bigquery.ex, lib/glific/gcs.ex, lib/glific/partners.ex, test/glific/bigquery_test.exs
Added some more information in the logs to get more details on the GCS token error for an organization.
=> add logs to get more details on the issue

lib/glific/saas/onboard.ex, lib/glific/saas/queries.ex, lib/glific_web/controllers/api/v1/onboard_controller.ex, lib/glific_web/router.ex, test/glific/partners/onboard_test.exs, test/glific_web/schema/message_media_test.exs
=> add the remaining bits and pieces for SaaS implementation

lib/glific/contacts/contact.ex, lib/glific/partners/organization.ex, lib/glific/saas/onboard.ex, lib/glific/saas/queries.ex
=> Format results before converting it to json

lib/glific/groups.ex
=> check first, then insert

lib/glific/partners/invoice.ex, mix.exs
=> fix appsignal error on invoices

api.docs/includes/_media.md, lib/glific_web/resolvers/media.ex, lib/glific_web/schema/media_types.ex
=> add blob uploads

lib/glific/flows/case.ex, lib/glific/flows/flow_context.ex, lib/glific/flows/router.ex, test/glific/flows/flow_context_test.exs
=> store selected in an array by itself

lib/glific.ex, lib/glific/flows/message_vars_parser.ex, lib/glific/flows/webhook.ex, test/glific/flows/action_test.exs, test/glific/flows/message_vars_parser_test.exs
=> encode to json map

lib/glific/flows/message_vars_parser.ex, lib/glific/flows/webhook.ex, test/glific/flows/action_test.exs, test/glific/flows/message_vars_parser_test.exs
=> webhook issue

lib/glific/seeds/seeds_dev.ex
=> Seeder updates

lib/glific/flows/action.ex, lib/glific/flows/case.ex, lib/glific/flows/contact_action.ex, lib/glific/flows/flow_context.ex, lib/glific/flows/message_vars_parser.ex, lib/glific/flows/router.ex, test/glific/flows/message_vars_parser_test.exs
=> get parent/child stuff working

lib/glific/clients/stir.ex, lib/glific/flows/webhook.ex
=> stir education

lib/glific/flows/localization.ex, test/glific/flows/localization_test.exs
There is an issue with the location-based attachments.  We were missing an edge case there.
=> Not able to update hindi messages on flows

lib/glific/third_party/bigquery/bigquery.ex
=> bigquery timeouts

lib/glific/flows/contact_action.ex, lib/glific/messages.ex
Replace params while sending the template.
=> Parse messages

lib/glific.ex, lib/glific/flows/action.ex, lib/glific/flows/contact_field.ex, lib/glific/flows/flow_context.ex, lib/glific/flows/router.ex, test/glific/flows/action_test.exs, test/glific/flows/flow_context_test.exs
=> Eex support for update contact from flows

lib/glific/flows/contact_action.ex, lib/glific/flows/flow_context.ex, lib/glific/messages.ex, lib/glific/templates/interactive_templates.ex, test/glific/interactive_templates_test.exs, test/glific/messages_test.exs, test/glific_web/schema/interactive_template_test.exs
Added message body from interactive content as message body
=> Interactive message

lib/glific/clients/digital_green.ex, lib/glific/contacts/import.ex, lib/glific/flows/contact_action.ex, lib/glific/flows/flow_context.ex, lib/glific/messages.ex, lib/glific/templates/interactive_templates.ex, lib/glific/third_party/sheets/api_client.ex, test/glific/bigquery_test.exs, test/glific/interactive_templates_test.exs, test/glific/messages_test.exs, test/glific_web/schema/interactive_template_test.exs
=> Dynamic Attachments

lib/glific/clients/digital_green.ex
Added function to evaluate next defined slot for DG in dynamic wait for response
=> DG: Next defined slot evaluation

lib/glific/clients/digital_green.ex
=> dg changes

lib/glific/providers/gupshup/api_client.ex
Added 30 seconds timeout when applying for the new template in Gupshup
=> Added timeout while applying for template

lib/glific/messages.ex, lib/glific/templates/interactive_templates.ex, test/glific/messages_test.exs
Creating message media on sending interactive message
=> Creating message media on sending interactive message

lib/glific/searches.ex
=> Added one more clause

lib/glific/messages.ex
=> Cleanups for validating media

api.docs/includes/_flow_labels.md, api.docs/includes/_search.md, assets/gql/flow_label/by_id.gql, assets/gql/flow_label/count.gql, assets/gql/flow_label/fields.frag.gql, assets/gql/flow_label/list.gql, lib/glific/flows.ex, lib/glific/flows/flow_label.ex, lib/glific/messages.ex, lib/glific/searches.ex, lib/glific/searches/search.ex, lib/glific_web/resolvers/flow_labels.ex, lib/glific_web/schema.ex, lib/glific_web/schema/flow_label_types.ex, lib/glific_web/schema/message_types.ex, lib/glific_web/schema/search_type.ex, test/glific_web/schema/flow_label_test.exs, test/glific_web/schema/search_test.exs, test/support/fixtures.ex
- Updated documentation for Flow label APIs
- Added APIs for list, count, and get flow label by id
- Added Fixture for Flow label
- Added test cases for flow label API(GraphQL)
- Updated search with flow label
- Added test cases for search API with flow label as filter
=> Tags to Labels

priv/repo/migrations/20210210023539_add_indexes.exs, priv/repo/migrations/20210806092436_update_indexes.exs
Added indexes for faster query execution
=> Added missing contexts for faster execution of queries

lib/glific/flows.ex
Added check for expression on `enter-a-flow`
=> Export flow not working in dynamic enter flow expression

api.docs/includes/_messages.md, assets/gql/messages/fields.frag.gql, lib/glific/messages/message.ex, lib/glific_web/schema/message_types.ex, test/glific_web/schema/message_test.exs
- Added the name of a staff member or the Admin on the message that is sent manually and flow name in case it is automatically sent from the flow
=> Adding Conversation messages send by 

lib/glific/flows.ex, lib/glific/messages.ex, lib/glific_web/controllers/exotel_controller.ex, lib/glific_web/flows/webhook_controller.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/router.ex, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs, test/glific_web/schema/flow_label_test.exs, test/glific_web/schema/search_test.exs
=> first crack at integrating exotel optin

config/config.exs, lib/glific/clients.ex, lib/glific/clients/digital_green.ex, lib/glific/jobs/minute_worker.ex
=> Clients daily cron

api.docs/includes/_flows.md, assets/gql/flows/flow_get.gql, assets/gql/flows/flow_release.gql, lib/glific/application.ex, lib/glific/contacts/simulator.ex, lib/glific/state.ex, lib/glific_web/resolvers/contacts.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific/simulator_test.exs, test/glific/state_test.exs, test/glific_web/schema/contact_test.exs, test/glific_web/schema/flow_test.exs
Added support to update flow as free and busy as per user
=> Genserver: to manage user level restriction on flows

lib/glific/flows/case.ex, test/glific/flows/case_test.exs
Added fixes for has a number between taking number with special character as valid response
=> FlowEditor: has number between

assets/gql/flows/flow_get.gql, lib/glific/clients.ex, lib/glific/clients/digital_green.ex, lib/glific/flows.ex, lib/glific/state.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific_web/schema/flow_test.exs
Added support to show in error message user name that is currently using the flow
=> Flow usage name display

lib/glific/flows/action.ex, lib/glific/flows/broadcast.ex, lib/glific/flows/flow.ex, lib/glific/flows/flow_context.ex, lib/glific/messages.ex, lib/glific/processor/consumer_flow.ex, priv/repo/migrations/20210817103124_background_flows.exs, test/glific/flows/action_test.exs, test/glific/flows/flow_context_test.exs, test/glific/flows/node_test.exs
Adding support to background flows
=> Background flows

lib/glific/triggers/helper.ex, lib/glific/triggers/trigger.ex
added fixes for trigger add and update when trigger has frequency as weekly
=> added fixes for trigger add and update

lib/glific/providers/gupshup/contacts.ex, lib/glific/state.ex, test/glific/processor/consumer_flow_test.exs, test/glific_web/schema/flow_test.exs
Updated flow busy message as per [issue](https://github.com/glific/glific-frontend/issues/1600)
=> Updated message when flow is used by staff

.tool-versions, assets/package-lock.json, assets/package.json
Downgrade node to 14 because of the compatibility issues with node-saas.
=> node updates

lib/glific/clients/digital_green.ex, lib/glific/third_party/navanatech/navanatech.ex, lib/glific_web/controllers/exotel_controller.ex
- Add more logs to check the errors
- Validate text, in case it's media url.
=> Digital Green Extension

lib/glific/messages.ex, lib/glific/state.ex, lib/glific/triggers/helper.ex, test/glific/flows_test.exs
=> fix potential app signal issues

lib/glific/clients/stir.ex, lib/glific/flows/router.ex, lib/glific/flows/webhook.ex, lib/glific/messages.ex, lib/glific/third_party/dialogflow/sessions.ex
=> lets store inserted_at time for results fields also

mix.exs
=> Updated mix version

api.docs/includes/_interactive.md, lib/glific/seeds/seeds_dev.ex, lib/glific/templates/interactive_templates.ex, test/glific/flows/contact_action_test.exs, test/glific/messages_test.exs
1. updating interactive message content text as header
2. updating interactive message content caption as text
3. updating translations
=> Interactive updates

lib/glific/erase.ex, lib/glific_web/flows/flow_editor_controller.ex, lib/glific_web/resolvers/messages.ex, test/glific/flows/message_vars_parser_test.exs, test/glific_web/flows/flow_editor_controller_test.exs, test/glific_web/schema/flow_test.exs
=> send in user id when sending hsm messages also in resolvers

lib/glific/clients.ex, lib/glific/clients/avanti.ex
Avanti consulting: fetching contact information and reports from Plio BigQuery instance and disseminating report data to contacts through HSM templatees
=> Avanti consulting integration

lib/glific/providers/gupshup/template.ex, lib/glific/templates.ex, lib/glific/templates/session_templates.ex, test/glific/templates_test.exs
updated regex to calculate number of parameters for template having more than 9 variables
=> Added fix for number of template variable

priv/data/flows/completion.json
=> updated completion json

lib/glific/flows/router.ex
=> Split by collection membership: Flow results not parsing

lib/glific/flows/case.ex, test/glific/flows/case_test.exs, test/glific_web/providers/gupshup/controllers/message_controller_test.exs
=> first steps towards more functions for floweditor

lib/glific/providers/gupshup/contacts.ex
https://github.com/glific/glific-frontend/issues/1735
=> Don't add the country code  in phone for all the contacts 

lib/glific/partners/invoice.ex
- Added condition for handling in case of an error in updating the subscription
- Logging the error message in case of an error
=> Stripe fixes for handling cancelled subscription

config/config.exs, lib/glific/conversations.ex, lib/glific/flows/broadcast.ex, lib/glific/flows/broadcast/broadcast_worker.ex, lib/glific/jobs/minute_worker.ex, mix.exs
=> Feature/tagv3 broadcast (#1867)

lib/glific/communications/message.ex, lib/glific/flows/flow_context.ex, lib/glific/flows/node.ex
=> add more telemetry to glific

lib/glific/clients/stir.ex
- added check for incorrect MT id
=> Stir Webhook: added check for incorrect MT id

lib/glific/flows/action.ex
https://discord.com/channels/717975833226248303/780402199679336469/912653400523554847
=> Added key name to the contact field

api.docs/includes/_interactive.md, lib/glific/flows/contact_action.ex, lib/glific/messages.ex, lib/glific/templates/interactive_template.ex, lib/glific/templates/interactive_templates.ex, lib/glific_web/schema/interactive_template_types.ex, priv/repo/migrations/20211124063048_interactive_msg_optional_title.exs, test/glific/messages_test.exs
- Added support for making title option while sending an interactive message
- Updated docs
- Updated APIs
- Added test cases
=> Interactive msg optional title

lib/glific/processor/consumer_flow.ex
- Parsing signup link message as a normal message
=> removing skip message

lib/glific/clients/nayi_disha.ex, lib/glific/clients/nayi_disha/data.ex, priv/repo/seeds/20200723172939_add_glific_data.exs
=> ND added translation

lib/glific/clients/stir.ex
- Added support to show previous month videos
=> added previous month video support

lib/glific/searches.ex
Hiding blocked contacts from chat screen
=> Hiding blocked contacts from chat screen

lib/glific/flows/flow_context.ex
=> cleanups in contact history

lib/glific/contacts/import.ex, test/glific/contacts_test.exs, test/glific_web/schema/contact_test.exs
- Fixed contact import with optin time in db
- Updated testcases for same
=> Import Contact: Optin time fixes

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
updated schema and queue table for stats table
=> updating schema and queue table

lib/glific/clients/stir.ex
1. Change the inactive reminder day values from 15 to 7.
=> Change the inactive reminder day - STIR

lib/glific_web/resolvers/consulting_hours.ex, test/glific_web/schema/consulting_hour_test.exs
- Added skip organization clause while fetching consulting hours from DB
- Added test cases
=> Consulting Hour: Fixes while updating

lib/glific/clients/nayi_disha/data.ex, lib/glific/flows.ex, lib/glific/flows/action.ex, lib/glific/flows/contact_action.ex, lib/glific/flows/localization.ex, lib/glific/flows/node.ex, lib/glific/seeds/seeds_migration.ex, lib/glific_web/resolvers/consulting_hours.ex, priv/data/flows/template.json, test/glific/contacts_test.exs, test/glific_web/schema/contact_test.exs
- removing localization from node struct and parsing node-specific localization within action
=> Memory optimizations in node

lib/glific/triggers/trigger.ex, test/glific/triggers_test.exs
- Added check for frequency as `does not repeat`
- Added testcases for trigger with frequency as `does not repeat` and `daily`
=> Bug/Trigger: frequency with `does not repeat`

lib/glific/flows/webhook_log.ex, lib/glific_web/schema/webhook_log_types.ex, test/glific/flows/webhook_test.exs
- added filter by contact_phone
- added testcases
=> WebhookLogs: added phone as filter

lib/glific/seeds/seeds_dev.ex
- Added Seeder for Contact History
=> Contact History: Added Seeders

lib/glific/messages.ex
=> (#1907) production bug

lib/glific/messages.ex
=> Allow ogg format for audio files

api.docs/includes/_flows.md, assets/gql/flows/contact_resume.gql, lib/glific/flows/flow_context.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific_web/schema/flow_test.exs
=> Add missing docs and tests

lib/glific/clients/nayi_disha/data.ex
1. File clean up remove the line and extra spaces
=> Nd clean for data loading file

lib/glific/communications/message.ex, lib/glific/seeds/seeds_dev.ex, lib/glific_web/schema/message_types.ex
Added subscriptions for simulator
=> Added subscriptions for simulator 

lib/glific_web/controllers/stripe_controller.ex
=> added check for billing exist

lib/glific/searches.ex
- Added check to prevent blocked contacts from search list
=> filtering blocked contact

test/glific/searches_test.exs
- Added test cases for search-multi to exclude blocked contacts from results
=> Searches: search_multi testcase

lib/glific/flows/router.ex
- Added support for split by contact fields.
=> Split by contact fields.

lib/glific.ex
- relaxing the validations a bit more
=> Bug fixes and updates

lib/glific.ex, lib/glific/clients.ex, lib/glific/clients/arogya_world.ex, lib/glific/triggers.ex
=> Tweak things for AW Project

lib/glific/clients/arogya_world.ex, lib/glific/flows/action.ex, lib/glific/flows/contact_action.ex
- @allow user to put dynamic label in the flows.
=> Allow user to put dynamic label

lib/glific/clients/arogya_world.ex
Add upload functionality for participant responses
Not added
=> Add upload functionality for participant responses

lib/glific/third_party/gcs/gcs_worker.ex
=> gcs bucket

lib/glific/clients.ex, lib/glific/clients/arogya_world.ex
Added question response score and removed hourly tasks
=> Arogya world: Added question response score and removed hourly tasks 

lib/glific/clients/arogya_world.ex
- Added label for static message and dynamic message.
=> dynamic labels

lib/glific/clients/arogya_world.ex
Change file URL's and format of data
=> AW: Change file URL's and format of data

lib/glific/clients/arogya_world.ex
- Use clean strings (without spaces) for encoding
- Send 0 as code if no response matches
- Send all the contacts in the response sheet even if they didn't answered
=> AW: updates

lib/glific_web/resolvers/triggers.ex
- Added log when trigger is deleted
=> Trigger: Logs for trigger deletion

lib/glific/flows/flow_context.ex, lib/glific/flows/message_vars_parser.ex, test/glific/flows/message_vars_parser_test.exs
- Fix the bug when we send non-standard messages.
=> Message var parser issue

lib/glific/providers/gupshup/worker.ex, test/glific/communications_test.exs
- Added message handler for simulator
=> Message Handler: Fixes

lib/glific/searches/full.ex
added query run_include_labels for checking contact ids with labels
=> Searches: search with labels

lib/glific/clients/arogya_world.ex, lib/glific_web/router.ex
AW: program updates based on batches
=> AW: program updates based on batches

lib/glific/clients/bandhu.ex, lib/glific/flows/webhook.ex
=> Webhook header issues

lib/glific/clients/bandhu.ex, lib/glific/clients/sol.ex, test/glific/clients_test.exs
=> SOL updates 

lib/glific/clients/bandhu.ex, lib/glific/flows/message_vars_parser.ex, test/glific/flows/message_vars_parser_test.exs
=> Message var parser issues

lib/glific/templates/interactive_templates.ex, lib/glific_web/flows/flow_editor_controller.ex, lib/glific_web/router.ex, test/glific_web/flows/flow_editor_controller_test.exs
Added single interactive message API for floweditor.
Added testcases for same
=> Added single interactive message api for floweditor

.github/workflows/continuous-integration.yml, config/config.exs, elixir_buildpack.config, lib/glific/appsignal.ex, lib/glific/clients/arogya_world.ex, lib/glific/partners.ex, lib/glific/searches.ex, mix.exs
- Made elixir changes for production 
- Update mix.exs
- Added new oban plugin to remove warning etc
=> Elixir upgrade fixes

lib/glific/flows/contact_action.ex, lib/glific/flows/router.ex, lib/glific/messages.ex, lib/glific/processor/consumer_flow.ex, lib/glific/templates/interactive_templates.ex
- Added dynamic variable support in the 
- Use interactive message-id if it's exists
=> Dynamic interactive messages

lib/glific/clients.ex, lib/glific/clients/arogya_world.ex, lib/glific/clients/mukkamaar.ex
AW: encoding updates and uncommented hourly jobs
=> AW: encoding updates and uncommented hourly jobs

lib/glific/providers/gupshup/template.ex
- There was a critical issue while fetching the HSM template.
=> Hot fix session updates 

priv/repo/migrations/20220328113810_swap_primary_oban_indexes.exs
=> Oban enhancements 

lib/glific/flows/flow_context.ex, lib/glific/third_party/bigquery/bigquery.ex, lib/glific_web/resolvers/flows.ex
=> better job with infinite loop detection

lib/glific/seeds/seeds_dev.ex, test/glific/flows/contact_action_test.exs, test/glific/messages_test.exs, test/glific_web/schema/interactive_template_test.exs
=> #2152 fixes

lib/glific/flows/flow_context.ex, lib/glific/processor/consumer_flow.ex
- Add the keyword who triggered the flow to default flow results.
=> Add the keyword who triggered the flow to default flow results

lib/glific/clients/arogya_world.ex
=> Arogya participant file fixes

lib/glific/clients/arogya_world.ex
=> credo fixes on master

lib/glific/providers/gupshup_enterprise/message.ex, lib/glific_web/providers/gupshup_enterprise/router.ex, lib/glific_web/providers/gupshup_enterprise/shunt.ex
Added support to receive audio message in Guphsup Enterprise
=> Hotfix/audio receiving in Enterprise

lib/glific/flows/templating.ex, lib/glific_web/resolvers/messages.ex, mix.exs
=> Appsignal issue

lib/glific/clients/arogya_world.ex
Fixed arogya hourly tasks error and added 0 as response code when no answer is present as suggested by Jack from the University of oregon team
=> Fixed arogya hourly tasks error and added 0 as response code 

priv/repo/migrations/20210417183726_update_message_number.exs
=> Update message number improvements 

lib/glific/clients/arogya_world.ex
Arogya fixed week number and 0 as a number not parsing in csv issue
=> Arogya fixed week number and 0 as a number not parsing in csv issue

lib/glific/clients/digital_green.ex
- Updated count for the DG intertive messages.
=> Feature db

api.docs/includes/_messages.md, lib/glific/messages/message.ex, lib/glific_web/schema/message_types.ex
Updated message object return
Updated doc
=> Broadcast id in message type

lib/glific/clients/arogya_world.ex
Upload participant cron fix for arogya
=> Upload participant cron fix for arogya

api.docs/includes/_flows.md, assets/gql/flows/broadcast_stats.gql, lib/glific/clients/mukkamaar.ex, lib/glific/flows/broadcast.ex, test/glific_web/schema/flow_test.exs
- Updated API documentation
- Fixed error returning in Flow broadcast stats API
- Restructured format of the stats
=> sending broadcast error count

lib/glific_web/resolvers/messages.ex
=> Hotfix: Set a limit to send messages to a group

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
Target issue is #2230  
We need bsp_status for few ngo and this information is quite helpful for some reports
=> Added bsp_status to bigquery

lib/glific/flows/webhook.ex, test/glific/flows/webhook_test.exs
=> Webhook was failing in case of a list response.

assets/gql/contacts/by_phone.gql, lib/glific/contacts.ex, lib/glific_web/resolvers/contacts.ex, lib/glific_web/schema/contact_types.ex, test/glific_web/schema/contact_test.exs
Target issue is #2257  
Before submitting a pull request, please ensure that you mark these tasks.
=> Get contact by phone

lib/glific/flows/broadcast.ex
Added fix to check broadcast contacts are valid contacts and once processed their processed_at is updated with status as pending
=> Hotfix/ Flow broadcast

api.docs/includes/_organizations.md, lib/glific/partners.ex, lib/glific/seeds/seeds_dev.ex, test/glific_web/schema/organization_test.exs, test/glific_web/schema/provider_test.exs
Target issue is #2263  
Removing Chatbase from provider listing
=> Disable Chatbase from listing

lib/glific.ex, lib/glific/contacts/import.ex, lib/glific/flows/contact_field.ex, test/glific/contacts_test.exs
Target issue is #2268 
Updated import functionality to add contact fields
=> Enhanced upload contacts to add fields 

lib/glific/flows/action.ex, lib/glific/messages.ex, test/glific/messages_test.exs
Target issue is #2282  
Before submitting a pull request, please ensure that you mark these tasks.
=> Dialog flow intent issue

api.docs/includes/_profiles.md
=> added more docs for profile

lib/glific/clients/kef.ex
1. Added messages for the English, Hindi and Kannada for the report messages
=> KEF report messages changes for different language

lib/glific/flows/flow_label.ex, lib/glific_web/flows/flow_editor_controller.ex
Improving the flow editor controller
- While fetching the resources from the table we are reducing the list to select single fields. We can achieve that by using a simple select statement.   
=> flow editor controller improvement

lib/glific/flows/flow_context.ex
=> Recent inbounds

lib/glific/flows/action.ex
=> Dialog flow: Process custom input also apart from last user message. 

lib/glific/clients/tap.ex
- Removed unwanted spaces from the cell text in a excel sheet.
=> Tap clean input spaces

lib/glific/flows/action.ex, lib/glific/flows/contact_action.ex, lib/glific/templates/interactive_templates.ex
- Enable dynamic attachments for the interactive message.
=> Dynamic attachment interactive message 

.github/workflows/continuous-integration.yml
=> Temp: updating the versions in CI

api.docs/includes/_session_templates.md, lib/glific/providers/gupshup_enterprise/template.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/seeds/seeds_migration.ex, lib/glific/templates/session_templates.ex, test/glific/templates_test.exs, test/support/fixtures.ex
=> Updated HSM categories according to the latest documentation for gupshup

lib/glific/clients/kef.ex
1. Kef school id fixes to match the exact school id
=> School id changes

lib/glific/clients/kef.ex
1. Previously matching the school id with user input now changed it to the user input for the school id and based on that getting the school id
=> KEF - userinput school id match

test/glific/partners/billing_test.exs, test/support/ex_vcr/update_monthly_usage.json
=> Hotfix: updating VCR with monthly user usage testcase

lib/glific/clients/kef.ex, lib/glific/clients/tap.ex, lib/glific/contacts.ex, lib/glific/profiles.ex, lib/glific/third_party/bigquery/bigquery.ex
Fixed a few issues while switching the profile
Disable BQ credentials if we receive permission denied error
=> Few changes in Contact profile

api.docs/includes/_flows.md, assets/gql/flows/fields.frag.gql, assets/gql/flows/list.gql, lib/glific/flows.ex, lib/glific/flows/flow.ex, lib/glific/partners.ex, lib/glific_web/schema/flow_types.ex, priv/repo/migrations/20220725085345_update_flows_is_pinned.exs, test/glific/flows_test.exs, test/glific/partners/partners_test.exs, test/glific_web/schema/flow_test.exs
Target issue is #2341  
- Added a new column for is_pinned to distinguish pinned flows
- Added is_pinned as filter to query easily
=> Pinning flows in Flows screen

lib/glific/flows/action.ex, lib/glific/templates.ex
Target issue is #2323  
closes #2323 
=> Disable unexpected message for appsignal

lib/glific/flows.ex, test/glific/flows_test.exs
Target issue is #2325   
This is to fix the error message 
=> Error fixed

api.docs/includes/_flows.md, lib/glific/state/flow.ex, lib/glific/state/simulator.ex, lib/glific/state/state.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific/state_test.exs
Target issue is #2339   
Adding support to take over flow when flow is currently is busy
=> Flow: Take Over

lib/glific/contacts.ex, test/glific/contacts_test.exs
Target issue is #2334 
Added additional check to prevent deletion of `NGO Main Account` for an organization
=> Delete contact restriction

lib/glific_web/schema/organization_types.ex, test/glific_web/schema/organization_test.exs
Target issue is #2361   
- staff role added for organization api
=> staff role added for organization api

lib/glific/flows/templating.ex, lib/glific/partners.ex, lib/glific_web/resolvers/partners.ex, test/glific/partners/partners_test.exs
=> Pull organisation services even the org is suspended. 

lib/glific/caches.ex, lib/glific/caches/cache_behaviour.ex, lib/glific/flows.ex, lib/glific/partners.ex, lib/glific_web/schema/flow_types.ex, lib/glific_web/schema/users_types.ex, test/glific/bigquery_test.exs, test/glific/caches_test.exs, test/glific/dialogflow/sessions_test.exs, test/glific/partners/partners_test.exs
=> Goth access token

lib/glific/flows/flow_context.ex, lib/glific/messages.ex, lib/glific/notifications.ex, lib/glific/notifications/notification.ex, lib/glific/partners.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/templates.ex, test/glific_web/providers/gupshup/controllers/message_controller_test.exs
The target issue is #1777  
Now we will create a notification whenever an HSM will get approved and rejected. 
=> fixes typo and other changes

lib/glific/communications/message.ex, lib/glific/flows/action.ex, lib/glific/flows/router.ex, lib/glific/providers/gupshup/message.ex
=> Fix some typos and message orders. 

lib/glific_web/resolvers/messages.ex
Target issue is #2377   
Updating the error message when sending a message to a collection with more than 30 contacts
=> Update Error message

lib/glific/clients.ex, lib/glific/clients/reap_benefit.ex
Adding webhook for reapbenefit to send/receive data to/from their Frappe app
=> Consulting: RB frappe webhook

lib/glific/clients/reap_benefit.ex, lib/glific/message_conversations.ex, lib/glific/messages/message_conversation.ex, lib/glific/providers/gupshup/message.ex, lib/glific/providers/message_behaviour.ex, lib/glific_web/providers/gupshup/controllers/billing_event_controller.ex, lib/glific_web/providers/gupshup/controllers/message_controller.ex, lib/glific_web/providers/gupshup/plugs/shunt.ex, lib/glific_web/providers/gupshup/router.ex, priv/repo/migrations/20220823091156_add_message_conversations.exs, test/glific/message_conversations_test.exs, test/glific_web/providers/gupshup/controllers/billing_event_controller_test.exs, test/support/fixtures.ex
Target issue is #2349  
- Created new table named `messages_conversations` to store conversation when `billing-event` is received for a new conversation
=> Message Conversations

lib/glific/contacts.ex, lib/glific/flows/contact_action.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/templates/interactive_templates.ex
- Enabled dynamic interactive message for ids.
- Added seeds for information notification.
- Extended list profile for interactive messages.
=> Interactive message ids

lib/glific/providers/gupshup/message.ex, lib/glific/providers/message_behaviour.ex, lib/glific_web/providers/gupshup/controllers/billing_event_controller.ex, test/glific_web/providers/gupshup/controllers/billing_event_controller_test.exs
Removing raising error and reporting to appsignal
=> Message Conversations: disabling logs

lib/glific/flows/contact_field.ex, lib/glific/flows/contact_setting.ex, test/glific/flows/action_test.exs, test/glific/flows/contact_setting_test.exs, test/support/fixtures.ex
Target issue is #2401  
- Added support to capture user preferred language at profile level when language is switched
- Added Testcases
=> Profiles: adding support to capture prefered language

lib/glific/partners.ex, lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/saas/queries.ex, lib/glific/seeds/seeds_optins.ex, priv/repo/seeds/20200723172939_add_glific_data.exs, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs, priv/repo/seeds_credentials.exs
=> Partner APIs setup. 

lib/glific/partners/provider.ex, lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/providers/gupshup/template.ex, lib/glific/providers/gupshup_enterprise/template.ex, lib/glific/templates.ex, test/glific/templates_test.exs
The target issue is #2385  
- Added an API for deleting the templates. 
- Cleaned up code more and get the bsp at the same place for the system.
=> Partner API cleanups

api.docs/includes/_contacts.md, api.docs/includes/_profiles.md, lib/glific/contacts.ex, lib/glific/contacts/contact.ex, lib/glific/contacts/contact_history.ex, lib/glific_web/schema/contact_types.ex, lib/glific_web/schema/profile_types.ex, test/glific/profiles_test.exs, test/glific_web/schema/contact_test.exs
- Added profile id filters in contact history
=> Profile: APIs

lib/glific/clients/reap_benefit.ex
=> Frappe webhook

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
- Updated schema for message schema.
=> Fix bigquery issues 

api.docs/includes/_flows.md, api.docs/includes/_groups.md, lib/glific/access_control.ex, lib/glific/access_control/group_role.ex, lib/glific/groups.ex, lib/glific/groups/group.ex, lib/glific_web/schema/contact_types.ex, lib/glific_web/schema/group_types.ex, priv/repo/migrations/20220905054418_add_groups_permissions.exs, test/glific/access_control_test.exs
Target issue is #2234 
Implementing Phase 2 of Roles and Permission
-  Implementing permission in collections
- Updated documentation
=> Roles and Permission: Phase 2

assets/gql/session_templates/sync.gql, lib/glific_web/schema/session_template_type.ex
Target issue is #2419 
Changed sync_hsm API from query to mutation. 
=> changed query to mutation

lib/glific/profiles.ex
=> Profiles: Saving contact fields to first profile

lib/glific/providers/gupshup_enterprise/template.ex, lib/glific/seeds/seeds_migration.ex, lib/glific/templates.ex, test/glific/partners/onboard_test.exs
- There was an error while fetching the hsm templates.
=> Issues while fetching the data from BSP.

lib/glific/access_control.ex, lib/glific/flows/broadcast.ex, lib/glific/messages.ex, lib/glific/seeds/seeds_migration.ex
- Parse params when we send a hsm template via broadcast. 
- Fix other credo errors
=> Fixes params

lib/glific/messages.ex, priv/repo/migrations/20220915095949_add_indexes_for_bigquery_updates.exs
=> Added indexes

lib/glific/appsignal.ex, lib/glific/contacts.ex, lib/glific/partners.ex, lib/glific/partners/provider.ex, lib/glific/providers/gupshup/partner/partner_api.ex
Remove hardcoding of BSP from some modules.
Added  few oban plugins from APP signal.
=> Code refactoring and removed some BSP hardcoding

lib/glific/messages.ex, test/glific_web/providers/gupshup/controllers/message_controller_test.exs
=> Fix session media message to group

lib/glific/profiles.ex, test/glific/profiles_test.exs
=> Profile: Hotfix for profile switching

lib/glific/flows.ex
=> Appsignal: Flow required fields

lib/glific/clients/reap_benefit.ex
ReapBenefit: Sending Frappe user ID from webhook
=> Consulting: Reapbenefit

lib/glific/flows/case.ex, lib/glific/flows/flow.ex, priv/data/flows/test.json, test/glific/flows_test.exs
Target issue is #2431
- Added validation for Flows to check if a flow wait-for-response has keywords
- Updated Test Workflow flow which is used in testcases
=> Flows: Validation for flow keywords

lib/glific/partners.ex, lib/glific/saas/queries.ex
Fixed the issue of APP update credentails.
=> Fixed the issue for APP id whenever we onboard an organisation. 

lib/glific/flows.ex, lib/glific/flows/flow_context.ex, lib/glific/messages.ex, lib/glific/processor/consumer_flow.ex
- Add more information to the contact history while killing all the flows. 
- Code refactoring 
- Code cleanups
=> Clean contact history and marked all the flows completed. 

lib/glific/contacts.ex, lib/glific/flows/broadcast.ex, lib/glific/flows/flow_context.ex, lib/glific/flows/wait.ex
It looks like when we wake up flows it might take some time to process and meanwhile we wake them up again.
=> Handle multiple message issue

lib/glific/flows/case.ex, priv/data/flows/test.json
Added a fix for case validation and updated testcases for same
=> Flow validation

lib/glific/flows/action.ex, lib/glific/flows/flow_context.ex
- Added more data while re sting the context.
=> Added logs while resetting the context

lib/glific/messages/message_conversation.ex, lib/glific/providers/gupshup/message.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, priv/repo/migrations/20220823091156_add_message_conversations.exs, priv/repo/migrations/20220923073920_update_message_conversation.exs
- Making `message_id` optional in the message conversation
- Updating Bigquery schema for the message conversation
- Sending contact phone in BQ message conversation table
=> Enhancements: Message conversation

lib/glific/flows.ex, lib/glific/flows/flow.ex, test/glific/flows_test.exs, test/glific_web/schema/flow_test.exs
Issue #2465 
- Added error message when starting an inactive flow using API
=> Flows: Restricting inactive flows

config/runtime.exs, lib/glific/appsignal.ex, lib/glific_web/providers/gupshup/plugs/shunt.ex, lib/glific_web/providers/gupshup_enterprise/shunt.ex, lib/glific_web/router.ex, test/glific/access_control_test.exs
- Added two custom name spaces in the project and ignored all the cases for that.
=> Setup namespaces in AppSignal

lib/glific/flows/case.ex, lib/glific/flows/flow.ex, lib/glific/flows/localization.ex, lib/glific/flows/node.ex, lib/glific/flows/router.ex, priv/data/flows/test.json
Target issue is #2481  
- Added additional check to validate on wait-for-response case
- Updated testcase
- Fixed some typos
=> Enhancement: Flow Editor Case validation

lib/glific/third_party/asr/google_asr.ex, lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, lib/glific/third_party/gcs/gcs.ex, lib/glific/third_party/navanatech/navanatech.ex, lib/glific/third_party/sheets/api_client.ex
Issue #2474  
- Added schema for message broadcasts and message broadcast contacts
- Added queue table queries to sync data
- Fixed few typos
=> Bigquery: Syncing broadcast tables

lib/glific/seeds/seeds_migration.ex
=> Async bigquery

lib/glific/clients/digital_green.ex
1. Crop calendar changes as per the json inserted
2. Sending media messages based on the day
=> Dg Telangana changes

lib/glific/partners.ex, lib/glific/third_party/bigquery/bigquery.ex, test/glific/bigquery_test.exs, test/glific/partners/partners_test.exs
- Cleanups for errors and warning when updating BQ credentials
- Updated testcases
=> Bigquery: Insufficient Permission issue

lib/glific/messages/message.ex, lib/glific/providers/gupshup/api_client.ex, lib/glific/providers/gupshup_enterprise/api_client.ex, lib/glific/providers/gupshup_enterprise/message.ex, lib/glific_web/resolvers/messages.ex
Target issue is #2493   
- Added support media interactive messages in Gupshup Enterprise
=> Gupshup Enterprise: Media interactive msg

lib/glific/providers/gupshup_enterprise/api_client.ex, lib/glific/providers/gupshup_enterprise/message.ex, lib/glific/providers/gupshup_enterprise/worker.ex
Target issue is #2500   
- Added support for sending media templates(image, video, document)
- Added support for sending media templates(image, video, document) with buttons
=> Gupshup Enterprise: Media Templates

lib/glific/flows/webhook.ex, test/glific/flows/webhook_test.exs
- Allow list responses in the data.
=> Allow list responses in the webhook

config/config.exs, lib/glific/erase.ex, lib/glific/groups/contact_group.ex, lib/glific/jobs/minute_worker.ex
- Reindexer jobs
- Added timestamp for contact groups
=> Re indexer oban jobs

coveralls.json, lib/glific/clients/digital_green.ex, lib/glific/flows/webhook_log.ex, lib/glific/mails/mail_log.ex, lib/glific/stats.ex, lib/glific/third_party/sheets/sheet.ex, lib/glific/third_party/sheets/sheet_data.ex, lib/glific/third_party/sheets/sheets.ex, lib/glific_web/resolvers/sheets.ex, lib/glific_web/schema.ex, lib/glific_web/schema/group_types.ex, lib/glific_web/schema/search_type.ex, lib/glific_web/schema/sheet_types.ex, lib/glific_web/schema/trigger_types.ex, priv/repo/migrations/20221012062208_add_sheets.exs
Target issue is #2519
Target issue is #2517    
**Notes**
- Create two new tables for storing sheets data namely `sheets` and `sheets_data`
- Added CRUD APIs for Google sheets
- Added schema for `sheets` and `sheets_data`
=> Google Sheets

assets/gql/contacts/import.gql, lib/glific/contacts/import.ex, lib/glific_web/resolvers/contacts.ex, test/glific/contacts_test.exs, test/glific_web/schema/contact_test.exs
Target issue is #2523  
#2524 
-  The organization_id was nil if it's not getting from the params. To resolve that I'm using user organization_id
-  In the case of super admin we receive collection in the params. 
=> organization id fix

lib/glific/flows/webhook.ex
Webhook bug while receiving a list response
=> List webhook

lib/glific/clients.ex, lib/glific/clients/digital_green_jharkhand
1. Client file code added for the digital green Jharkhand
=> Client file initiation for the Dg jharkhand

lib/glific.ex, lib/glific/flows/action.ex, lib/glific/templates/interactive_templates.ex, lib/glific_web/flows/flow_editor_controller.ex, lib/glific_web/router.ex, lib/glific_web/tenants.ex, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs, priv/repo/seeds/20201006012223_v0_5_0_alter_glific_data.exs
Target issue is #2536 
- Added API for listing sheets in flow editor
- Fixed few typos
=> Google Sheet: Added Flow API for sheets

lib/glific/clients.ex, lib/glific/clients/pehlay_akshar.ex
- Init PehlayAkshar client
- Added webhook for loading ssending template message
=> Consulting: PehlayAkshar

lib/glific/flows/message_vars_parser.ex, test/glific/flows/message_vars_parser_test.exs
- Now we allow hyper also in contact variable.
=> Contact fields with updates

lib/glific/flows/message_vars_parser.ex, priv/data/flows/completion.json, test/glific/flows/message_vars_parser_test.exs
=> Date function

lib/glific/searches.ex
- Sort search results based on the contact last message at.
=> Sort messages based on last message at

lib/glific/clients.ex, lib/glific/flows/action.ex, lib/glific/flows/flow_context.ex, lib/glific/third_party/sheets/sheets.ex, priv/repo/migrations/20221012062208_add_sheets.exs
Target issue is #2539 
- Added new node in Flow editor to support linking google sheet
- Fixed few typos
=> Google Sheet: New Flow editor node

assets/gql/sheets/by_id.gql, assets/gql/sheets/count.gql, assets/gql/sheets/create.gql, assets/gql/sheets/delete.gql, assets/gql/sheets/fields.frag.gql, assets/gql/sheets/list.gql, assets/gql/sheets/update.gql, coveralls.json, lib/glific/clients/pehlay_akshar.ex, lib/glific/third_party/sheets/sheet.ex, test/glific/message_conversations_test.exs, test/glific/sheets_test.exs, test/glific_web/schema/sheet_test.exs, test/support/fixtures.ex
- Added unit testcases for sheet integration
- Added GraphQL testcases
=> Google Sheets: Testcases

lib/glific/third_party/sheets/sheets.ex
Parsing variable in the sheet row name
=> Google Sheet: Parsing sheet row variable

lib/glific/clients.ex, lib/glific/clients/digital_green_jharkhand.ex, lib/glific/messages.ex
syncing master with codes stored in extension files
=> Extensions

lib/glific/partners/billing.ex
- Hotfixes for recent API changes in proration
=> Stripe: Hotfixes for recent API changes

lib/glific/flows/action.ex
=> Flow label issue

lib/glific/flows/periodic.ex, lib/glific/partners/out_of_office.ex
=> Default flow

lib/glific.ex, lib/glific/flows/case.ex, test/glific/flows/case_test.exs
=> Parse may be a number/1

lib/glific/clients.ex, lib/glific/clients/oblf.ex
1. Client file initialization for the oblf
=> Client file for OBLF

lib/glific/third_party/bigquery/bigquery.ex, lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific/bigquery_test.exs, test/glific_web/registration_controller_test.exs, test/support/conn_case.ex, test/support/fixtures.ex
=> Usrer optin

lib/glific/flows/action.ex
=> Set run result node

lib/glific/flows/router.ex
Enable a node to split by random
https://github.com/glific/glific/issues/2587
=> Split by random

lib/glific/flows.ex, lib/glific/flows/broadcast.ex, lib/glific/flows/broadcast/message_broadcast.ex, lib/glific/flows/flow_context.ex, lib/glific/processor/consumer_flow.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, priv/repo/migrations/20221202103552_add_default_results_to_message_broadcast.exs, test/glific/flows_test.exs
Start flow with default results
=> Start flow with default results

lib/glific/flows.ex, test/glific_web/schema/flow_test.exs
Target issue is #2598  
- Added support for importing/exporting interactive template
- Added testcases for same
=> Flows: Import/Export Interactive Templates

lib/glific/erase.ex, rel/overlays/Procfile
Issue #2612 
Cleaning up big tables periodically
=> Erase: Webhooks, Message Conversations and Flow contexts

lib/glific/flows/contact_action.ex, lib/glific/messages.ex
=> Messages: added empty body check

lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
Cleaning BQ logs with org_id for easier search in Logflare
=> BigQuery: Clean logs

config/config.exs, lib/glific/partners.ex
Experimenting with cron and active organization time to sync more data
=> BigQuery: Sync Delays

lib/glific/clients/reap_benefit.ex, lib/glific/jobs/minute_worker.ex, lib/glific/partners.ex
- Added a supervisor to run all the organizations parallelly. 
- Enabled that for bigquery only for now. 
We will see how that performs and then enable it for few more workers.
=> Process organisations Parallelly  for bigquery   

lib/glific/clients/nayi_disha.ex
=> Nayidisha: sending english content as default

lib/glific/third_party/sheets/sheets.ex
=> Gsheet: Hotfix

lib/glific/flows/action.ex
=> Flows: Save Flow Results node

lib/glific/clients/tap.ex, lib/glific/erase.ex
1. Format the school id from the users
2. Making the short form of the school id
3. Returning the waba link with short form school id
=> Tap school id changes

priv/repo/migrations/20230104054512_add_missing_indexes.exs
=> DB: Indexes

lib/glific/flows/flow_context.ex
=> Contact History: Cleanups

lib/glific/contacts.ex
=> Simulator: restricting deletion

lib/glific/clients/reap_benefit.ex
=> Modified name logic while creating user in frappe

lib/glific/flows.ex
=> Flows: exporting nodes efficiently

lib/glific/flows.ex
=> importing flows issues

api.docs/postman/api_collection.json
Target issue is #2644 
- Updated documentation for contacts API
- Updated filter documentation for search API
- Updated postman collection version to 2.1.0
=> Updated postman documentation

lib/glific/flows/action.ex
=> FlowEditor: Support for EEX evaluation in Flowresults

api.docs/includes/_sheets.md, lib/glific/third_party/sheets/sheet.ex, lib/glific/third_party/sheets/sheets.ex, lib/glific_web/schema/sheet_types.ex, priv/repo/migrations/20230131111743_add_sheet_data_count.exs
=> Gsheet Integration: adding gsheet rowcount

api.docs/includes/_session_templates.md, lib/glific/providers/airtel/message.ex, lib/glific/providers/airtel/template.ex, lib/glific/providers/gupshup/template.ex, lib/glific/providers/gupshup_enterprise/template.ex, lib/glific/providers/template_behaviour.ex, lib/glific/templates.ex, lib/glific/templates/template_worker.ex, lib/glific_web/resolvers/templates.ex, lib/glific_web/schema/session_template_type.ex, test/glific/templates_test.exs
Target issue is #1805  
- Added API to bulk apply templates
- Updated documentation
=> Templates: Bulk apply to Gupshup

lib/glific/providers/gupshup/template.ex
=> Bulk Template: Cleaning rows

lib/glific_web/schema/generic_types.ex, test/glific_web/schema/search_test.exs
Using datetime instead of date when using daterange filter
=> APIs: daterange filter

lib/glific_web/resolvers/media.ex
We recently changed the signature of the media upload function and that cause the issue.  
closes: https://github.com/glific/glific/issues/2685
=> Fixed message media response type. 

README.md
- Updated readme for contributors to ask the team for oban pro keys
- Fixed typo
=> Updated readme for contributor

lib/glific/seeds/seeds_dev.ex, lib/glific/seeds/seeds_flows.ex, lib/glific/seeds/seeds_migration.ex, priv/data/flows/ab_test.json, priv/data/flows/multiple_profile.json, priv/data/flows/multiple_profile_creation.json, priv/repo/seeds/20200723172939_add_glific_data.exs, test/glific/groups_test.exs, test/glific/interactive_templates_test.exs, test/glific/state_test.exs, test/glific_web/schema/group_test.exs, test/glific_web/schema/interactive_template_test.exs
=> Flows: Adding more seed flows

lib/glific/mails/balance_alert_mail.ex
#2562 
1. Changed the subject for low balance as per the issue description
=> Change email subject for low balance

priv/repo/migrations/20230314073042_add_unique_index_to_new_contact_id_for_users.exs
#2701 
1. Migration to make contact_id unique
=> Make contact_id unique for users table

config/runtime.exs, lib/glific/flows/broadcast.ex
=> Make broadcast configurable

lib/glific/flows/flow_context.ex, lib/glific/jobs/minute_worker.ex, priv/repo/migrations/20230316080512_add_reason_column_to_flow_context.exs
#2664 
1. Added a new column reason in the flow_contexts table
2. Added a reason for the flow killed
=> Fill the reason in the context table

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
#2712
1. Add a reason column to the flow_contexts table in bigquery
=> Changes for bigquery schema

lib/glific/providers/gupshup/template.ex
=> Hotfix: Bulk Apply template

lib/glific/seeds/seeds_flows.ex, priv/data/flows/ab_test.json
Updated UUIDs of collections and Flows in seed flows
=> Fixes: UUIDs for Seed Flows

lib/glific/flows/flow_count.ex
Target issue is #2560
Appsignal error, fixed by adding echo constraint
=> add foreign key constraint #2560

lib/glific/mails/balance_alert_mail.ex, lib/glific/providers/balance_worker.ex
Target issue is #2669 
Make it a bit more flexible. $1 is really low since now all conversations are charged
=> make low_balance email a bit more proactive for larger amounts

assets/gql/organizations/delete_test.gql, lib/glific/partners.ex, lib/glific_web/resolvers/partners.ex, lib/glific_web/schema/organization_types.ex, test/glific/partners/partners_test.exs, test/glific_web/schema/organization_test.exs
Target issue is #1958   
Improve the experience for the NGO
=> add support to delete all messages and contacts for org

api.docs/includes/_contacts.md, lib/glific/clients/common_webhook.ex, lib/glific/contacts.ex, lib/glific_web/schema/contact_types.ex, test/glific_web/schema/contact_test.exs
Allow user to filter the contact by name or phone
=> filter contact by name or phone

lib/glific/flows/contact_field.ex
=> Trim the field key before putting to contact filed

lib/glific/seeds/seeds_dev.ex, lib/glific/seeds/seeds_migration.ex, test/glific/templates_test.exs, test/support/fixtures.ex
=> Changed category from OTP to Authentication

api.docs/includes/_interactive.md, lib/glific/templates/interactive_templates.ex, lib/glific_web/schema/interactive_template_types.ex, test/glific_web/schema/interactive_template_test.exs
=> Interactive Template: Search with Body

lib/glific/searches.ex
Target issue is #2696 
Adding id as secondary order by when last_communication_at is same
=> Search: Duplicate entering in load more

lib/glific/groups.ex, lib/glific/misc/flags.ex, lib/glific/providers/airtel/api_client.ex, lib/glific/providers/airtel/message.ex, lib/glific_web/resolvers/templates.ex, test/glific_web/schema/contact_test.exs, test/glific_web/schema/flow_test.exs, test/glific_web/schema/interactive_template_test.exs, test/glific_web/schema/organization_test.exs, test/glific_web/schema/provider_test.exs, test/glific_web/schema/session_template_test.exs, test/glific_web/schema/user_test.exs
Target issue is #2495  
Init organization with default fun_with_flags values
=> Organization: Init Fun with Flags

lib/glific_web/flows/flow_editor_controller.ex
=> Flows: Listing only active flows

lib/glific/flows.ex, lib/glific/flows/action.ex, lib/glific/flows/broadcast.ex, lib/glific/flows/flow.ex, test/glific/flows/action_test.exs
=> Start Session: Adding Exclusion

lib/glific_web/schema/organization_types.ex
=> add optin_flow_id to all the right places

coveralls.json, lib/glific.ex, lib/glific/providers/gupshup/api_client.ex, lib/glific/providers/gupshup/contact_worker.ex, lib/glific/providers/gupshup/contacts.ex
=> Guphsup: Fetching multi-page opted contacts

lib/glific/clients/pehlay_akshar.ex
Added two webhook for the quiz flow having the following functionality
1. For getting the interactive message button counts and button values
2. Checking the correct user response with the google sheet
=> PA - Quiz flow webhook changes

lib/glific/contacts/import.ex
=> Fixed language bug for tamil

config/runtime.exs, lib/glific_web/controllers/exotel_controller.ex, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs
Target issue is #2780 
Handle multiple exotel numbers
Tested for backward compatibility. Working good 👍
=> Handle multiple exotel numbers

lib/glific/clients/common_webhook.ex, lib/glific_web/templates/layout/_user_menu.html.heex, lib/glific_web/templates/layout/root.html.heex, lib/glific_web/templates/live/stats_live.html.heex, lib/glific_web/templates/user_session/new.html.heex
Added common webhook for jugalbandi
=> Jugalbandi: OpenAI common webhook

assets/gql/tickets/by_id.gql, assets/gql/tickets/count.gql, assets/gql/tickets/create.gql, assets/gql/tickets/delete.gql, assets/gql/tickets/fields.frag.gql, assets/gql/tickets/list.gql, assets/gql/tickets/update.gql, lib/glific/tickets.ex, lib/glific/tickets/ticket.ex, lib/glific_web/resolvers/tickets.ex, lib/glific_web/schema.ex, lib/glific_web/schema/ticket_types.ex, test/glific/tickets_test.exs, test/glific_web/schema/ticket_test.exs, test/support/fixtures/tickets_fixtures.ex
=> Ticketing: CRUD APIs

lib/glific/clients/common_webhook.ex, lib/glific/clients/lahi.ex, lib/glific/clients/suno_sunao.ex, lib/glific/third_party/asr/google_asr.ex
Added Google ASR as common webhook
=> Feature: ASR common webhook

lib/glific/trackers.ex
=> Fix issues with summarizing tracker stats

lib/glific/clients/kef.ex
KEF client file webhook changes
1. Webhook to check if the current existing worksheet code is completed or not
2. Webhook to send buttons value and the count in response for Gsheet
3. Webhook to check the correct answer for Gsheet integration
=> KEF webhook changes

README.md, lib/glific_web/controllers/landing_page_controller.ex, lib/glific_web/router.ex, lib/glific_web/templates/landing_page/landing_page.html.heex, lib/glific_web/views/landing_page_view.ex, test/glific_web/page_controller_test.exs
Target issue is #2807 
Making this minimal landing page lets the developer know that the backend is up and running
- [ x ] Ran `mix setup` in the repository root and test.
- [ x ] If you've fixed a bug or added code that is tested and has test cases. 
- [ x ] Coding standard and conventions are followed. https://docs.google.com/document/d/1rfU33IjS-ioiIH0TBWpxoLsdyyYdI1tDrqr5HCRIb98/edit?usp=sharing
=> Glific Backend Landing Page

lib/glific/messages.ex, lib/glific/messages/message.ex, test/glific/messages_test.exs, test/glific_web/schema/message_test.exs
=> learn more about ecto and empty values

lib/glific/clients/bandhu.ex, lib/glific/clients/common_webhook.ex
Added support for ChatGPT with voice
=> ChatGPT: Added support for voice gpt

lib/glific/clients/common_webhook.ex
=> ChatGPT: Voice GPT enhancement

lib/glific/flows.ex
- Keeping draft version of flow revision till 48 hrs
- Added log when a new flow revision is published
=> Bug: Saved flow revision getting lost

lib/glific/flows.ex, lib/glific/flows/flow_revision.ex, lib/glific_web/flows/flow_editor_controller.ex, lib/glific_web/resolvers/flows.ex, priv/repo/migrations/20230616045651_add_flow_revision_author.exs, test/glific/erase_test.exs, test/glific/flows_test.exs
- Storing flow revision author in the DB
- Updating testcases
=> Flows: Added flow revision author

lib/glific/clients/common_webhook.ex
Checking if the prompt is passed in webhook body and appending it while making API call
=> GPT: Adding prompt option

lib/glific/templates.ex, lib/glific_web/schema/session_template_type.ex, test/glific_web/schema/session_template_test.exs
=> Category filter for templates

lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/providers/gupshup/template.ex
This is a review PR.
Target issue is #2828
This is an enhancement to allow Template category change by Meta.
=> Enhancement: Template allow category change

lib/glific/flows.ex, lib/glific/flows/flow.ex, lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific_web/schema/flow_types.ex, priv/repo/migrations/20230627145331_add_labels_to_flows.exs, test/glific/flows_test.exs, test/glific_web/schema/session_template_test.exs
Target issue is #2845
This is a review PR
=> added label column to flows table

lib/glific/groups.ex, lib/glific/reports.ex, lib/glific_web/resolvers/groups.ex, lib/glific_web/schema/group_types.ex
**Summary**
Target issue is #2871 
**Notes**
- Created a function `import_collection` which returns a string of contacts in collection.
- Done changes in schema.
=> Target issue #2871

lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.html.heex
=> Add card for non opted contacts

lib/glific/reports.ex, lib/glific/seeds/seeds_migration.ex, lib/glific_web/templates/live/stats_live.html.heex
=> Add Cards for Monthly Flows

lib/glific/clients.ex, lib/glific/clients/udhyam.ex, lib/glific_web/schema/group_types.ex, lib/glific_web/templates/live/stats_live.html.heex, test/glific/sheets_test.exs
Changing default GCS file structure
=> Client: Udhyam GCS structure

lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.html.heex
=> Revert "Add Cards for Monthly Flows"

lib/glific/partners/export.ex
=> Exports: fixes for endtime

lib/glific_web/plugs/api_auth_plug.ex
=> Fixed auth bug 

lib/glific/third_party/sheets/google_sheets.ex, lib/glific/third_party/sheets/sheets.ex, lib/glific_web/plugs/api_auth_plug.ex
=> sending API error for gsheet

lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.ex, lib/glific_web/templates/live/stats_live.html.heex
=> Add Cards for Monthly Incoming, Outgoing and HSM Messages

lib/glific_web/plugs/api_auth_plug.ex
Added patch for subscription auth
=> Added patch for subscription auth

lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.ex, lib/glific_web/templates/live/stats_live.html.heex
Target issue is #2877 
Provides summary of the kind of notifications.
=> Notification Chart 

lib/glific/contacts.ex, lib/glific/reports.ex, lib/glific/searches.ex, lib/glific_web/templates/live/stats_live.html.heex
=> add timeout to search multi

lib/glific/reports.ex
Monthly error messages and notifications were not monthly, but rather total. Fixed SQL queries that were causing this.
=> fixed notification and error message queries to be monthly

lib/glific/partners/export.ex, lib/glific/reports.ex, test/glific_web/schema/export_test.exs
Target issue is #2917 
1. Updated export data format
=> Updated OrganizationExportData API to return data field as JSON string

test/glific/groups_test.exs
**Summary**
Target issue is https://github.com/glific/glific/issues/2871
**Notes**
Added test cases
=> Test case for export collection

lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.html.heex
=> Add Cards for Flows Started and Completed

lib/glific/third_party/bigquery/bigquery_worker.ex, mix.exs
=> fix bigquery order issue

.github/workflows/continuous-integration.yml, .tool-versions, elixir_buildpack.config, lib/glific/providers/gupshup/partner/partner_api.ex, mix.exs, test/glific/access_control_test.exs, test/glific/contacts_test.exs, test/glific/flows_test.exs, test/glific/messages_test.exs, test/glific_web/schema/api/router_test.exs, test/glific_web/schema/contact_group_test.exs, test/glific_web/schema/credential_test.exs, test/glific_web/schema/export_test.exs, test/glific_web/schema/flow_test.exs, test/glific_web/schema/group_test.exs, test/glific_web/schema/language_test.exs, test/glific_web/schema/message_test.exs, test/glific_web/schema/notification_test.exs, test/glific_web/schema/organization_test.exs, test/glific_web/schema/provider_test.exs
Upgrade of elixir exposed some flakiness in our tests. lets try to kill this asap
=> Lets try to minimize flaky tests

lib/glific/erase.ex
=> clean up erase, optimize it to delete more messages first

lib/glific/contacts.ex, lib/glific/erase.ex
=> when we update any field, update the updated_at time also

lib/glific/processor/consumer_tagger.ex, test/glific/processor/consumer_tagger_test.exs
Removing new contact tag dependency
=> Bug: removing tag dependency

lib/glific/reports.ex, lib/glific/seeds/seeds_dev.ex, lib/glific/stats.ex, lib/glific/stats/stat.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, lib/glific_web/templates/live/stats_live.ex, priv/repo/migrations/20230801091505_stats_add_conversations_column.exs
=> conversations from stats table

lib/glific/third_party/gcs/gcs_worker.ex
=> lets start using flow column in message_media table

config/config.exs, lib/glific/erase.ex, lib/glific/third_party/gcs/gcs_worker.ex, lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific_web/registration_controller_test.exs
=> clean up and lets do more work in cronjobs

lib/glific/clients/lahi.ex
1. Extended the common webhook for lahi
=> Lahi extension update for the bhasini

lib/glific/contacts.ex, priv/data/flows/completion.json
=> Flows: Active profile id at flow level

lib/glific_web/schema/search_type.ex, test/glific_web/schema/search_test.exs
Target issue is #2988  
fix the date format in the advance search
=> SavedSearches: Date Filter Bugfix

lib/glific/communications/mailer.ex, lib/glific/mails/balance_alert_mail.ex, lib/glific/mails/critical_notification_mail.ex, lib/glific/mails/report_gupshup_mail.ex, lib/glific/templates.ex, lib/glific_web/schema/search_type.ex, test/glific/templates_test.exs
Target issue is #2964  
Checking if we have already sent the mail in last 24 hours
=> report_gupshup: checking_the_last_mail_notification

assets/css/app.css, lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.ex, lib/glific_web/templates/live/stats_live.html.heex
Most Active Hour chart was left to be done in cont-ex. It's done now.
=> Most Active Hour in ContEx

lib/glific/third_party/asr/bhasini.ex
1. Increase API timeout for Bhasini
=> Increase api timeout for Bhasini 

lib/glific/clients/bandhu.ex
Few Error handling and updates
=> Client: Bandhu Webhook

lib/glific/erase.ex, priv/repo/migrations/20230818012026_add_indexes.exs, priv/repo/structure.sql
=> improve erase

lib/glific/clients/bandhu.ex
=> Bandhu: WB fixes

lib/glific/reports.ex
Target issue is #3048 
- Fixed bug while fetching weekly data
=> Dashboard bug fixes

lib/glific/flows/periodic.ex, lib/glific/notifications.ex, lib/glific/partners.ex, lib/glific/partners/organization.ex, lib/glific/partners/out_of_office.ex, lib/glific/partners/setting.ex, lib/glific/providers/balance_worker.ex, lib/glific_web/schema/organization_types.ex, lib/glific_web/templates/live/stats_live.ex, test/glific/partners/partners_test.exs
Target issue is #2600 
- Created new embedded schema for `setting` column in `organizations` table
- if `run_flow_each_time` field is set to true then we run the flow
=> Run default or out of office flow each time

lib/glific/clients/common_webhook.ex
1. Webhook for showing buttons and check response
=> Webhook changes for sheet interactive

lib/glific/reports.ex, lib/glific_web/templates/live/stats_live.ex
=> Internal Dashboard: Quickfixes

assets/css/app.css, lib/glific_web/templates/live/stats_live.ex, lib/glific_web/templates/live/stats_live.html.heex
- Made the charts stretch across the webpage evenly alongside the broadcast table.
- Fixed the width of the date column in broadcast table and margin of the table.
=> Internal Dashboard: UI Fixes

lib/glific/clients/common_webhook.ex
=> Common Webhook: Openllm

config/.env.test, lib/glific/reports.ex, lib/glific_web/schema/contact_types.ex, lib/glific_web/schema/contacts_field_type.ex, lib/glific_web/schema/flow_types.ex, lib/glific_web/schema/interactive_template_types.ex, lib/glific_web/schema/notification_types.ex, lib/glific_web/schema/session_template_type.ex, lib/glific_web/schema/sheet_types.ex, lib/glific_web/schema/trigger_types.ex, lib/glific_web/schema/users_types.ex, lib/glific_web/schema/webhook_log_types.ex, test/glific_web/schema/contacts_field_test.exs, test/glific_web/schema/flow_test.exs, test/glific_web/schema/interactive_template_test.exs, test/glific_web/schema/notification_test.exs, test/glific_web/schema/session_template_test.exs, test/glific_web/schema/sheet_test.exs, test/glific_web/schema/trigger_test.exs, test/glific_web/schema/user_test.exs, test/glific_web/schema/webhook_log_test.exs
=> Role:Restrict staff access

lib/glific/messages/message_media.ex, lib/glific/seeds/seeds_dev.ex, lib/glific_web/schema/message_media_types.ex, priv/repo/migrations/20230909123216_add_is_template_media_to_messages_media.exs, test/glific/communications_test.exs, test/glific/messages_test.exs, test/support/fixtures.ex
Optimizing message media table
=> Message Media: Table optimizations

lib/glific_web/schema/ticket_types.ex, lib/glific_web/schema/users_types.ex
Target issue is #3067 
##Description
providing access to the user to create and update tickets and also can access the current user.
=> Role:Provide access to staff

lib/glific/templates.ex
=> Templates: sync fixes

lib/glific/reports.ex, lib/glific_web/schema/middleware/authorize.ex, lib/glific_web/templates/live/stats_live.html.heex, test/glific_web/schema/user_test.exs
=> Authorize: Bugfixes

lib/glific_web/templates/live/stats_live.ex
=> Internal Dashboard: Tidy up bar chart labels to prevent clutter 

lib/glific/templates.ex
Target issue is #3099 
Removed Authentication category from templates (until WhatsApp adds support for it)
=> Templates: Removed Authentication Category 

lib/glific_web/endpoint.ex, lib/glific_web/templates/live/stats_live.ex
=> Audit: Restricting Cookies

lib/glific/communications/mailer.ex, lib/glific/mails/dashboard_mail.ex, lib/glific/stats.ex, lib/glific_web/templates/dashboard/dashboard.html.heex, test/glific_web/session_controller_test.exs
Target issue is #3112 
- This PR is just to test if the approach works in the production environment
- Only graphs should be displayed properly ( it will also be displayed as an attachment in GMAIL, etc.)
- Glific Logo, Discord Logo, LinkedIn Logo won't be displayed
=> CID method to send attachments

lib/glific/flows.ex, test/glific/flows_test.exs
=> Flows: flow listing bug

lib/glific/users.ex, lib/glific_web/plugs/api_auth_plug.ex, lib/glific_web/resolvers/users.ex, lib/glific_web/schema/users_types.ex, test/glific_web/api_auth_plug_test.exs
=> Audit: active user sessions

lib/glific/flows.ex, lib/glific/flows/action.ex, lib/glific/flows/case.ex, lib/glific/flows/flow.ex, lib/glific/flows/wait.ex, lib/glific_web/schema/flow_types.ex
Target issue is #3035
categorizing the flow errors while publishing the flow
=> Flows:Warning Categorizations

lib/glific_web/resolvers/contacts.ex, lib/glific_web/templates/dashboard/dashboard.html.heex
=> Contact:Remove_status from read only

lib/glific/clients/kef.ex
1. Kef new webhooks for watched videos, count of watched videos.
=> kef new webhooks

priv/repo/structure.sql
=> Bug: Ticketing Schema

lib/glific/third_party/bigquery/bigquery_worker.ex, mix.exs
=> make sure updated_at and retrieval query use similar conditions

lib/glific/seeds/seeds_migration.ex, test/glific/partners/onboard_test.exs, test/glific/templates_test.exs, test/support/fixtures.ex
=> Templates: Updating seed OTP template

assets/gql/tickets/fetch.gql, lib/glific/tickets.ex, lib/glific_web/resolvers/tickets.ex, lib/glific_web/schema/ticket_types.ex, test/glific_web/schema/consulting_hour_test.exs, test/glific_web/schema/ticket_test.exs, test/support/fixtures/tickets_fixtures.ex
Target issue is #3002
Download the support tickets in .csv or .xls format
=> Ticket:Download Support Tickets

lib/glific/flows.ex, lib/glific/seeds/seeds_flows.ex, test/glific_web/schema/flow_test.exs
Target issue is #3134
the current user name in coming along with the flow revision
=> Flows:Add user name in flow revision

lib/glific/processor/consumer_worker.ex
=> Revert "Caching Genserver state"

lib/glific/stats.ex, lib/glific_web/templates/dashboard/dashboard.html.heex
Target issue is #3112 
- Due to some unknown reasons the Graphs were not showing labels/legends in the production
- For a temporary Solution replace Graphs with numeric 
New Mail looks like this
Open to any suggestions
=> Mail V3: Replaced Graphs in Mail with Numeric Metric

assets/gql/tickets/bulk_update.gql, lib/glific/tickets.ex, lib/glific_web/resolvers/tickets.ex, lib/glific_web/schema/ticket_types.ex, test/glific_web/schema/ticket_test.exs
Target issue is #3124 
user can close the multiple tickets together
=> Ticketing System:Bulk closure

lib/glific/stats.ex, lib/glific/tickets.ex, lib/glific_web/templates/dashboard/dashboard.html.heex, test/glific/tickets_test.exs
1. Added a notification for ticketing when new ticket created
=> Added notification for the ticket

lib/glific/clients/kef.ex
=> KEF: Webhook fixes

lib/glific/templates.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, test/glific/templates_test.exs
Target issue is #3156  
while importing the template old attached template are not getting loss as previous
=> Session Template: Import template check existing template UUID 

lib/glific/tickets.ex, test/glific_web/schema/ticket_test.exs
Target issue is #3126  
Add the filter for phone number and name of the contact
=> feature/Support Tickets: add the filter for phone and name

assets/gql/flows/import_flow.gql, lib/glific/flows.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex, test/glific/tickets_test.exs, test/glific_web/schema/flow_test.exs
Target issue is #3078 
while importing the error with the previously used keyword should give an error
=> Flow:Import Error Message

lib/glific/erase.ex, lib/glific/flows/flow_context.ex, lib/glific/jobs/minute_worker.ex, test/glific/flows/flow_context_test.exs
=> lets restructure cron jobs, optimize it so things run

lib/glific/tickets.ex, lib/glific_web/schema/ticket_types.ex, test/glific_web/schema/ticket_test.exs
Target issue is #3126
correct the query in the ticketing
=> feature/Ticketing:filter records

assets/gql/tickets/fields.frag.gql, lib/glific/providers/balance_worker.ex, lib/glific_web/schema/ticket_types.ex, test/glific_web/schema/ticket_test.exs
=> Ticket System: fix schema

lib/glific/communications/mailer.ex, lib/glific/mails/report_gupshup_mail.ex
=> Email: Updating support mail group

README.md
Make README clearer + increase ease of use for new users.
=> Update README with suggested edits

README.md
=> add the changes requested by DPG

lib/glific/flows/flow.ex, priv/data/flows/test.json, test/glific/flows_test.exs
=> Flows: Language Alert

lib/glific/flows/action.ex, lib/glific/profiles.ex, test/glific/flows_test.exs
Target issue is #3227
the next node after the inteactive one should be a wait for response node
=> Flow: Next node after interactive should be wait for response

lib/glific/tickets.ex, lib/glific_web/schema/ticket_types.ex, test/glific_web/schema/ticket_test.exs
Target issue is #3126
add the body filter in the ticket filtration along with the name or phone
=> Ticketing system: add the body filter in tickets

lib/glific/flows/flow.ex, lib/glific/settings.ex, test/glific/flows_test.exs
Target issue is #3262  
Optimize code and fixed bug
=> Bug: Template-translation

lib/glific/tickets.ex, test/glific_web/schema/ticket_test.exs
Target issue is #3002
this is the feedback changes for the export support ticket
=> Ticketing System: export tickets

lib/glific/flows/flow.ex, lib/glific/settings.ex, priv/data/flows/test.json, test/glific/flows_test.exs
=> Flows: Template Translation Alert

lib/glific/clients/kef.ex
Adding new folder for a flow specific files
=> Client: KEF GCS structure

lib/glific/flows/flow.ex, lib/glific/triggers.ex
Target issue is #3276 and #3275 
Added fixes
=> Flows: hotfix for few issues

assets/gql/organizations/get_services.gql, lib/glific/misc/flags.ex, lib/glific/partners.ex, lib/glific/partners/organization.ex, lib/glific_web/schema/organization_types.ex, test/glific_web/schema/organization_test.exs
=> Auto Translate: Feature Flag

lib/glific/flows/translate/open_ai.ex, test/glific/flows/translate/open_ai_test.exs
=> Auto Translate: Bugfixes

lib/glific_web/schema/organization_types.ex
Exposes APIs for organization settings
=> Organization: Settings

api.docs/bruno/setup.md
Target issue is #3197   
Update setup steps for bruno
=> Bruno: Update setup steps

lib/glific/flows/translate/open_ai.ex, test/glific/flows/translate/open_ai_test.exs
=> Auto Translate: Parallel Translation

lib/glific/misc/flags.ex, lib/glific_web/schema/organization_types.ex
=> Organization: Updating API

lib/glific/flows/translate/export.ex, lib/glific_web/resolvers/flows.ex, lib/glific_web/schema/flow_types.ex
=> Auto Translate: Export without translation

lib/glific/providers/gupshup/partner/partner_api.ex
The function will download the given resource from the given url and returns the saved local path
Target issue is #3306   
=> Using local file path for the gupshup new template api

lib/glific/providers/gupshup/partner/partner_api.ex
=> Template: Applying media template using local path

lib/glific/providers/gupshup/partner/partner_api.ex
=> Bug: Error while applying media template

lib/glific/flows/flow.ex, test/glific/flows_test.exs
=> Automated flow tester: Show Node UUID 

api.docs/bruno/glific_api/Authentication/Create a new session for an existing user.bru, api.docs/bruno/glific_api/Authentication/Create a new user.bru, api.docs/bruno/glific_api/Authentication/Login.bru, api.docs/bruno/glific_api/Authentication/Renew an existing session.bru, api.docs/bruno/glific_api/Authentication/Reset Password.bru, api.docs/bruno/glific_api/Authentication/Send an OTP request to verify a phone number of existing user.bru, api.docs/bruno/glific_api/Authentication/Send an OTP request to verify a phone number.bru, api.docs/bruno/glific_api/Contact Group/Create Contact Group.bru, api.docs/bruno/glific_api/Contact Group/Update a Group with contacts to be added and contacts to be deleted.bru, api.docs/bruno/glific_api/Contact Group/Update groups to be added and groups to be deleted to a Contact.bru, api.docs/bruno/glific_api/Contact Tag/Create Contact Tag.bru, api.docs/bruno/glific_api/Contact Tag/Subscription for Create Contact Tag.bru, api.docs/bruno/glific_api/Contact Tag/Subscription for Delete Contact Tag.bru, api.docs/bruno/glific_api/Contact Tag/Update a Contact with tags to be added and tags to be deleted.bru, api.docs/bruno/glific_api/Contacts/Block a Contacts.bru, api.docs/bruno/glific_api/Contacts/Get All Contacts.bru
Target issue is 
Adding API Documentation for all APIs.
=> API Documentation

lib/glific/flows/flow.ex
Target issue is #3333 #3332 #3337
=> Automated flow tester: Deleted node template translation warning 

.gitignore, test/glific/templates_test.exs
Issue #3346 
Auto cleanup of files created during template creation tests
=> Template: Files created during test has been auto-removed

lib/glific/partners.ex, lib/glific_web/resolvers/partners.ex
=> Organization: Updating API response

lib/glific/flows/translate/google_translate.ex, lib/glific/flows/translate/translate.ex, lib/glific/misc/flags.ex, lib/glific/partners.ex, lib/glific/settings.ex
=> Auto translate: Cleanups

lib/glific/flows/translate/google_translate.ex
=> Auto translate: google translate fix

lib/glific/flows/translate/export.ex
=> Auto translate: Fix default language order

api.docs/bruno/glific_api/Flows/Copy a Flow.bru, api.docs/bruno/glific_api/Flows/Count all Flows.bru, api.docs/bruno/glific_api/Flows/Create a Flow.bru, api.docs/bruno/glific_api/Flows/Delete a Flow.bru, api.docs/bruno/glific_api/Flows/Export a Flow.bru, api.docs/bruno/glific_api/Flows/Get All Flows.bru, api.docs/bruno/glific_api/Flows/Get a flow.bru, api.docs/bruno/glific_api/Flows/Get a specific Flow by ID.bru, api.docs/bruno/glific_api/Flows/Import a Flow.bru, api.docs/bruno/glific_api/Flows/Publish a Flow.bru, api.docs/bruno/glific_api/Flows/Release a flow contact.bru, api.docs/bruno/glific_api/Flows/Reset flow counts for a specific flow.bru, api.docs/bruno/glific_api/Flows/Resume flow for a contact.bru, api.docs/bruno/glific_api/Flows/Start flow for a contact.bru, api.docs/bruno/glific_api/Flows/Start flow for a group contacts.bru, api.docs/bruno/glific_api/Flows/Terminate flows for a contact.bru, api.docs/bruno/glific_api/Flows/Update a Flow.bru
=> API Documentation: Flows

api.docs/bruno/glific_api/Organizations/Check for attachment support for the given user.bru, api.docs/bruno/glific_api/Organizations/Count all Organizations.bru, api.docs/bruno/glific_api/Organizations/Create an Organization.bru, api.docs/bruno/glific_api/Organizations/Delete an Organization.bru, api.docs/bruno/glific_api/Organizations/Get All Organizations.bru, api.docs/bruno/glific_api/Organizations/Get List of Organization Status.bru, api.docs/bruno/glific_api/Organizations/Get List of Timezones.bru, api.docs/bruno/glific_api/Organizations/Get Organization Services.bru, api.docs/bruno/glific_api/Organizations/Get a specific Organization by ID.bru, api.docs/bruno/glific_api/Organizations/Subscription for Collection Count.bru, api.docs/bruno/glific_api/Organizations/Subscription for Simulator release Copy.bru, api.docs/bruno/glific_api/Organizations/Subscription for Simulator release.bru, api.docs/bruno/glific_api/Organizations/Subscription for Wallet Balance.bru, api.docs/bruno/glific_api/Organizations/Update an Organization.bru
=> Bruno: API Documentation for Organization

lib/glific/groups/whatsapp_group.ex, lib/glific/partners.ex, lib/glific/providers/maytapi/api_client.ex, lib/glific/wa_group/wa_managed_phone.ex, lib/glific/wa_managed_phones.ex, priv/repo/migrations/20240117234740_add_wa_groups.exs, priv/repo/seeds/20200925010203_v0_4_1_alter_glific_data.exs, test/glific/groups/whatsapp_group_test.exs, test/glific/wa_managed_phones_test.exs, test/support/fixtures/wa_groups_fixtures.ex
- Update the set of actions we do after adding valid Maytapi credentials to automate few things
- Updated testcases
=> WA Groups: Callback optimizations

lib/glific/groups/group.ex, lib/glific/groups/whatsapp_group.ex, priv/repo/migrations/20240117234740_add_wa_groups.exs, test/glific/groups/whatsapp_group_test.exs, test/support/fixtures/wa_groups_fixtures.ex
- Storing WhatsApp group  id from maytapi in db
- Updating testcases
=> WA Groups: Group info

README.md
Added phno and msg details to start working with WA bot + some other minor updations.
=> Ngrok doc: Added phno and msg details to start working with WA bot

assets/gql/organizations/get_services.gql, lib/glific/misc/flags.ex, lib/glific/partners.ex, lib/glific/partners/organization.ex, lib/glific_web/schema/organization_types.ex, test/glific_web/schema/organization_test.exs
Target issue is #3380 
create the feature flag for whatsapp group feature
=> WA groups: enable the feature flag

lib/glific/wa_group/wa_message.ex, lib/glific/wa_messages.ex, priv/repo/migrations/20240117234740_add_wa_groups.exs, test/glific_web/providers/maytapi/controllers/message_controller_test.exs
=> wa_messages schema updates

assets/gql/wa_managed_phones/count.gql, assets/gql/wa_managed_phones/list.gql, lib/glific/wa_managed_phones.ex, lib/glific_web/resolvers/wa_managed_phones.ex, lib/glific_web/schema.ex, lib/glific_web/schema/wa_managed_phone_type.ex, priv/repo/migrations/20240117234740_add_wa_groups.exs, priv/repo/migrations/20240222064744_add_trigger_for_wa_message_number.exs, test/glific_web/schema/wa_managed_phone.exs
- Added Trigger for wa_message number
- Added APIs for wa_managed_phone
- Added testcases for wa_managed_phone
=> WA Group: Trigger and APIs for wa_managed_phone

config/.env.test, lib/glific/communications/wa_group_message.ex, lib/glific/providers/maytapi/message.ex, lib/glific/providers/maytapi/wa_messages.ex, lib/glific/templates.ex, lib/glific_web/schema/message_types.ex, test/glific/groups/whatsapp_message_test.exs
Target issue is #3344
adding support to send the media message like audio, image etc in the whatsapp group
=> WA group: send media in wa group

lib/glific/communications/message.ex, lib/glific/communications/wa_group_message.ex, lib/glific_web/schema/message_types.ex
=> WA Group: Subscriptions

.github/workflows/continuous-integration.yml
=> Continuous Integration: Upgrades

assets/gql/contact_wa_groups/sync.gql, assets/gql/groups/list.gql, assets/gql/wa_group_collection/list.gql, assets/gql/wa_groups/count.gql, assets/gql/wa_groups/list.gql, lib/glific/flows.ex, lib/glific/groups.ex, lib/glific/groups/wa_groups.ex, lib/glific/groups/wa_groups_collections.ex, lib/glific_web/resolvers/groups.ex, lib/glific_web/resolvers/wa_collection.ex, lib/glific_web/resolvers/wa_group.ex, lib/glific_web/schema.ex, lib/glific_web/schema/contact_wa_group_types.ex, lib/glific_web/schema/group_types.ex, lib/glific_web/schema/wa_group_types.ex, lib/glific_web/schema/wa_groups_collection_types.ex, test/glific/groups_test.exs, test/glific_web/schema/contact_wa_group_test.exs, test/glific_web/schema/group_test.exs, test/glific_web/schema/wa_group_collection_test.exs
Target issue is #3420
some chages in the api result format and name of the api
=> WA groups: bugfixes and api update

lib/glific/communications/wa_group_message.ex, lib/glific/groups/wa_groups_collections.ex, lib/glific/providers/maytapi/message.ex, lib/glific/wa_group/wa_message.ex, lib/glific_web/providers/maytapi/controller/message_controller.ex, lib/glific_web/resolvers/messages.ex, lib/glific_web/schema/message_types.ex, priv/repo/migrations/20240117234740_add_wa_groups.exs, test/glific/groups/whatsapp_message_test.exs
=> WA Group: Sending message to collection

lib/glific/searches.ex, lib/glific_web/schema/search_type.ex
=> Searches: Appending entity id

lib/glific/providers/maytapi/message.ex, lib/glific/searches.ex
Target issue is #3442 and #3443
=> Enhancement: WA Search

lib/glific_web/resolvers/groups.ex, lib/glific_web/resolvers/wa_group.ex, lib/glific_web/schema/wa_group_types.ex
Adding label in the WA group search
=> WA Search: Added label as filter

lib/glific/communications/wa_group_message.ex, lib/glific_web/providers/maytapi/controller/message_event_controller.ex, lib/glific_web/providers/maytapi/shunt.ex, test/glific_web/schema/wa_message_test.exs
=> Update bsp_status from the maytapi webhook after sending message

lib/glific/tickets.ex
Target issue is https://github.com/glific/glific/issues/3452
=> Tickets: consistent csv header and content ordering

lib/glific/communications/wa_group_message.ex, lib/glific/contacts/location.ex, lib/glific/providers/maytapi/message.ex, lib/glific/wa_group/wa_message.ex, lib/glific_web/providers/maytapi/controller/message_controller.ex, lib/glific_web/schema/message_types.ex, priv/repo/migrations/20240320135052_add_wa_message_in_location.exs, test/glific_web/providers/maytapi/controllers/message_controller_test.exs
=> WA Groups: Support for  receiving location messages

lib/glific/providers/maytapi/wa_messages.ex
=> WA Groups: sending caption with media message

lib/glific/providers/maytapi/wa_messages.ex, test/glific_web/schema/wa_message_test.exs, test/support/fixtures.ex
Hot fix: fixing sending media + caption, broke sending only media + tests
=> WA Group: Hotfix for media with caption

lib/glific/groups/wa_groups.ex, lib/glific/partners.ex, lib/glific/providers/maytapi/response_handler.ex, lib/glific/wa_managed_phones.ex, lib/glific_web/schema/message_types.ex, test/glific/groups/whatsapp_group_test.exs, test/glific/partners/partners_test.exs, test/glific/wa_managed_phones_test.exs
=> WA Group: Clean Callbacks on adding credentials

lib/glific/providers/maytapi/response_handler.ex
=> WA Group: Creating notification on error message

lib/glific/searches.ex, test/glific/searches_test.exs, test/glific_web/providers/maytapi/controllers/message_controller_test.exs, test/glific_web/schema/search_test.exs
=> WA Groups: Exclude dms and collection msgs fom wa_search_multi

lib/glific/clients/kef.ex
Target issue is #3480 
Could not replicate error so added logs for better clarity
=> Client: KEF GCS Error

lib/glific/flows/flow_context.ex, test/glific/flows/flow_context_test.exs
=> Flow Context: Added validations in flow context for contact_id and wa_group_id

lib/glific/messages.ex
=> BugFix: OTP Template

lib/glific/messages.ex, test/glific/messages_test.exs
=> Removed support for sending ogg audio in WABA

lib/glific/providers/maytapi/message.ex, test/glific/groups/whatsapp_message_test.exs
Target issue is #3471
handling the error when sending message in an empty collection
=> WA group: error handling in wa group collection

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
=> Bigquery: Schema Changes

lib/glific/flows.ex, lib/glific/flows/broadcast.ex, lib/glific/messages.ex, test/glific/flows_test.exs, test/glific_web/schema/flow_test.exs
Target issue is [#3482](https://github.com/glific/glific/issues/3482)
=> WABA collection: Handle the error when group_is is empty list

lib/glific/flows/translate/translate.ex, lib/glific/providers/maytapi/api_client.ex, lib/glific_web/providers/maytapi/shunt.ex, lib/glific_web/resolvers/flows.ex
=> Metrics: Autotranslate & WA Group

lib/glific/contacts/contact.ex, test/glific/contacts_test.exs
=> Contacts: Added validation in `fields` in contacts table

lib/glific/third_party/bigquery/bigquery.ex
=> BQ: sending specific error message incase of error

lib/glific/third_party/bigquery/bigquery_worker.ex, test/glific/bigquery_test.exs
Target issue is #3477
validating the data type in the contact table fields
=> BQ: contact fields validation

lib/glific/flows/action.ex, test/glific/flows/action_test.exs
Target issue is #3492
log the error when Unsupported action type occurs
=> Appsignal: log undefined action node error

lib/glific/groups/wa_groups.ex, lib/glific_web/schema/wa_group_types.ex, test/glific_web/schema/wa_group_collection_test.exs
=> WA Groups: Group Collections: Added Search for groups inside a group collection

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
=> Revert "Bigquery: Schema Changes"

lib/glific/clients/common_webhook.ex, lib/glific/third_party/open_llm/openLLM.ex
Minor changes in code based on updated APIs
=> Open LLM: API Updates

lib/glific/clients/bandhu.ex, test/glific/clients_test.exs
=> Fetch user profiles: handling results map structure in webhook function

lib/glific/clients/common_webhook.ex, lib/glific/third_party/openAI/chatGPT.ex
Added support for GPT vision as a common webhook
=> GPT: added support for GPT vision

lib/glific/flows/broadcast.ex, test/glific_web/schema/flow_test.exs
=> flow: broadcast flow to group when group is not found

lib/glific/mails/new_partner_onboarded_mail.ex, lib/glific/providers/gupshup/contacts.ex, lib/glific/saas/onboard.ex, test/glific/partners/onboard_test.exs
=> fix: added emails to be send

lib/glific/clients/common_webhook.ex, lib/glific/clients/kef.ex, lib/glific/clients/udhyam.ex, lib/glific/third_party/openAI/chatGPT.ex
=> GPT Enhancement and logs

lib/glific_web/schema/middleware/safe_resolution.ex, test/glific/partners/partners_test.exs, test/glific/processor/consumer_flow_test.exs
=> Generic error message

lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
=> Bigquery: Syncing schema Error

lib/glific/third_party/openAI/chatGPT.ex
- Adding support to use different models by passing model name in params
- Using [high fidelity](https://platform.openai.com/docs/guides/vision/low-or-high-fidelity-image-understanding) for images by default
=> GPT: Enhancements

config/dev.exs, lib/glific/flows/translate/export.ex, test/glific/flows/translate_test.exs, test/glific_web/schema/flow_l10n_test.exs
Target issue is #3446
Adding the node uuid at the last of the csv file
=> Translation: Show node uuid instead of action uuid

config/config.exs, lib/glific/jobs.ex, lib/glific/jobs/minute_worker.ex, lib/glific/third_party/gcs/gcs.ex, lib/glific/third_party/gcs/gcs_job.ex, lib/glific/third_party/gcs/gcs_worker.ex, priv/repo/migrations/20240515113612_add_gcs_job_type.exs
=> GCS: Media sync fixes

lib/glific/groups/wa_groups.ex, test/glific/groups/whatsapp_group_test.exs
=> WA groups: Ignore wa groups when group name is empty

lib/glific/clients/reap_benefit.ex, lib/glific/enums/constants/enums.ex, lib/glific/saas/onboard.ex, priv/repo/migrations/20240527105105_add_forced_suspension_enum.exs, test/glific/partners/onboard_test.exs, test/glific_web/schema/organization_test.exs
=> Organization: Added forced_suspension status 

lib/glific_web/router.ex
Target issue is #3538 
Notes:
[FunWithFlags documentation on csrf](https://github.com/tompave/fun_with_flags_ui/blob/master/README.md#mounted-in-phoenix)
=> FunWithFlags: Using separate pipe in router

api.docs/bruno/glific_api/SaaS/Reachout to support.bru, lib/glific/mails/new_partner_onboarded_mail.ex, lib/glific/notion.ex, lib/glific/saas/onboard.ex, lib/glific/saas/queries.ex, test/glific/partners/onboard_test.exs
=> T&C: Added org name in reachout api and  Notion updates

lib/glific/clients/common_webhook.ex, lib/glific/clients/reap_benefit.ex, lib/glific/third_party/openAI/chatGPT.ex, test/glific/third_party/openAI/chatGPT_test.exs
=> GPT: Filesearch

lib/glific/clients.ex, lib/glific/clients/arogya_world.ex, lib/glific/clients/avanti.ex, lib/glific/clients/balajanaagraha.ex, lib/glific/clients/bharat_rohan.ex, lib/glific/clients/digital_green.ex, lib/glific/clients/digital_green_jharkhand.ex, lib/glific/clients/kef.ex, lib/glific/clients/mukkamaar.ex, lib/glific/clients/oblf.ex, lib/glific/clients/pehlay_akshar.ex, lib/glific/clients/quest_alliance.ex, lib/glific/clients/reap_benefit.ex, lib/glific/clients/sol.ex, lib/glific/clients/stir.ex, lib/glific/clients/suno_sunao.ex, lib/glific/clients/tap.ex, lib/glific/clients/udhyam.ex, test/glific/clients_test.exs
=> Clients: Common functions issue

assets/gql/contact_groups/count.gql, lib/glific/groups/contact_groups.ex, lib/glific_web/resolvers/groups.ex, lib/glific_web/resolvers/messages.ex, lib/glific_web/schema/contact_group_types.ex, test/glific_web/schema/contact_group_test.exs
=> Messaging: Group message warning

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, lib/glific/tickets.ex, lib/glific/tickets/ticket.ex, priv/repo/migrations/20240605165834_add_flow_id.exs, test/glific_web/schema/ticket_test.exs, test/support/fixtures/tickets_fixtures.ex
=> Tickets: Flow ID

priv/repo/seeds/20200723172939_add_glific_data.exs, test/glific_web/schema/flow_label_test.exs
=> Clearing some default flow labels and contact fields

assets/gql/session_templates/fields.frag.gql, lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/providers/gupshup/template.ex, lib/glific/templates/session_templates.ex, lib/glific_web/schema/session_template_type.ex, priv/repo/migrations/20240614091422_add_allow_template_category_change_to_session_templates.exs, test/glific/templates_test.exs, test/glific_web/schema/session_template_test.exs
Target issue is #3553 
Changes the API so that it can accept either `True` or `False` value for `allowTemplateCategoryChange`.
=> allowTemplateChange

lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific_web/registration_controller_test.exs, test/glific_web/schema/wa_search_test.exs
=> Returning conn on errors when sending otp

lib/glific/clients/common_webhook.ex, lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/third_party/asr/bhasini.ex, lib/glific/third_party/bhasini/bhasini.ex, lib/glific_web/resolvers/interactives.ex, test/glific/groups/whatsapp_group_test.exs, test/glific_web/schema/session_template_test.exs
=> Bhasini integration: NMT & TTS

lib/glific/third_party/bigquery/bigquery_worker.ex
=> Bigquery: Added check for nil flow

lib/glific/notifications.ex, lib/glific/providers/balance_worker.ex
=> Optimized the frequency of sending mail notifications 

lib/glific/third_party/bhasini/bhasini.ex
=> Bhasini: translated text

lib/glific/contacts.ex, lib/glific/groups/wa_groups.ex, lib/glific_web/schema/contact_types.ex, lib/glific_web/schema/wa_group_types.ex, test/glific_web/schema/contact_test.exs
=> Contacts: added exclude groups

assets/gql/flows/fields.frag.gql, lib/glific/flows.ex, lib/glific/flows/flow.ex, lib/glific/seeds/seeds_flows.ex, lib/glific_web/schema/flow_types.ex, priv/repo/migrations/20240627071515_add_is_template_to_flows.exs, test/glific/flows_test.exs, test/glific_web/schema/flow_test.exs
Target issue is #3633 
Added `is_template` field in flows table as part of Template flows on UI.
=> Added `is_template` field in flows table 

lib/glific/partners.ex, lib/glific/third_party/gcs/gcs.ex
=> GCS: enable logs for gcs bucket

lib/glific/clients/common_webhook.ex, test/glific_web/schema/flow_test.exs
=> Bhasini TTS: parsing contact language

lib/glific.ex, lib/glific/clients/digital_green.ex, lib/glific/clients/pehlay_akshar.ex
=> Templates: generalising send template function

lib/glific/clients/common_webhook.ex, lib/glific/third_party/openAI/chatGPT.ex, test/glific/third_party/openAI/chatGPT_test.exs
=> OpenAI: GPT Citations

priv/data/flows/help.json, priv/data/flows/optin.json, priv/repo/seeds/20200723172939_add_glific_data.exs
=> Flows: Optin Node updates

lib/glific/providers/gupshup/message.ex
=> Messages: Added previewUrl flag in send text messages

lib/glific/providers/gupshup/message.ex
=> fix: revert preview url

lib/glific/contacts.ex, test/glific/contacts_test.exs, test/glific_web/schema/flow_test.exs
Target Issue is #3548 
Fixed bug using pattern matching and added additional test to cover nil input cases.
=> Bug Fix: Remedied error with nil input in maybe_update_contact

lib/glific_web/schema/session_template_type.ex
Returning the quality field in session templates api
=> Session template: return the quality field in api

lib/glific/mails/balance_alert_mail.ex, lib/glific/partners/saas.ex, lib/glific/templates/interactive_templates.ex, lib/glific/third_party/gigalixir.ex, test/glific/partners/onboard_test.exs
Removed the amount in low balance mail subject according to this [thread](https://discord.com/channels/717975833226248303/1262641433760759819)
=> Notification mails: Removed balance amount from low balance alert mail subject

lib/glific_web/resolvers/flows.ex
=> Add metric for template flows

lib/glific.ex, lib/glific/communications/message.ex, lib/glific/communications/wa_group_message.ex, lib/glific_web/controllers/api/v1/session_controller.ex, lib/glific_web/providers/gupshup/controllers/user_event_controller.ex, test/glific/glific_test.exs
=> GDPR: Masking phone numbers

config/dev.exs, lib/glific/seeds/seeds_flows.ex, lib/glific_web/resolvers/flows.ex
Setting is_template to true for some seeder flows and false for others
=> flows: refactoring flow in seeder

lib/glific/clients/common_webhook.ex
=> GPT: Voice to Voice

lib/glific/providers/gupshup/partner/partner_api.ex, test/glific/partners/partners_test.exs
=> Gupshup: Transfer Balance 

lib/glific.ex, lib/glific/misc/flags.ex, lib/glific/seeds/seeds_dev.ex, test/glific/access_control_test.exs, test/glific_web/schema/role_test.exs
=> Roles: Omit Glific Admin

lib/glific_web/flows/flow_editor_controller.ex, test/glific_web/flows/flow_editor_controller_test.exs
=> Flows: Not fetching template flows in floweditor 

lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3726 
- Added logs
- increased waiting time
=> OpenAI: Run timeout

lib/glific/clients/common_webhook.ex, lib/glific/third_party/openAI/chatGPT.ex, test/glific/third_party/openAI/chatGPT_test.exs
Target issue is #3735 
Validating Assistant ID before calling filesearch
=> OpenAI: Checking Assistant

lib/glific/clients/common_webhook.ex
Target issue is #3748  
Using Text to speech if source and target language are same
=> Bhasini: NMT TTS language check

lib/glific/clients/common_webhook.ex
Target issue is #3704 
- Validating Media
- Added logs and redirecting it to error
=> GPTVision: Validating URL

lib/glific/clients/common_webhook.ex, lib/glific/flows/webhook.ex
Target issue is #3704  
Cleaning up webhook error further
=> GPTVision: Webhook Error

lib/glific/clients/common_webhook.ex, lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3757  
Passing to failure when Filesearch time out
=> OpenAI: Handling webhook errors

lib/glific/contacts/import.ex, lib/glific/contacts/import_worker.ex, test/glific/contacts_test.exs, test/glific_web/schema/contact_test.exs
=> Contact import: Added empty name and language validations

lib/glific/clients/common_webhook.ex, lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3770  
Using OpenAI to create voice notes when target language is English
=> OpenAI: English TTS

lib/glific/third_party/asr/bhasini.ex, lib/glific/third_party/bhasini/bhasini.ex, lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3778 
The issue was when using just text to speech pipeline we need to pass iso code rather than language name
=> Bhasini: Text to Speech fixes

assets/gql/contacts/upload_report.gql, lib/glific/contacts/import.ex, test/glific/contacts_test.exs, test/glific_web/schema/contact_test.exs
=> Contact Import: Downloading reports works even if there are no errors in the upload process

lib/glific/clients/common_webhook.ex, lib/glific/third_party/openAI/chatGPT.ex, test/glific/third_party/openAI/chatGPT_test.exs
Target issue is #3777  
Validating Thread ID before passing to OpenAI
=> OpenAI: Handling Thread ID

lib/glific/templates.ex, test/glific/templates_test.exs
=> HSM template: Fix button validation

lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3776 
Cancel a run if the OpenAI times out and retry
=> OpenAI: Retry Mechanism

lib/glific/third_party/openAI/chatGPT.ex
Removing unnecessary code and default 10 tries from start
=> Bug: Sending OpenAI response

lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3790 & #3791  
Also increased time between subsequent run to 5 secs and improved error messages
=> OpenAI: Webhook Error Cleanups

lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
=> BQ: sync contact groups table in BQ

lib/glific/providers/maytapi/response_handler.ex, lib/glific/wa_messages.ex, test/glific/groups/whatsapp_message_test.exs, test/glific_web/schema/wa_message_test.exs
=> WA group: Fix the flow type of send messages

lib/glific/clients/common_webhook.ex, lib/glific/third_party/asr/bhasini.ex, lib/glific/third_party/bhasini/bhasini.ex
=> Bhasini: STT

lib/glific/clients/common_webhook.ex, lib/glific/contacts.ex, lib/glific/third_party/asr/bhasini.ex
=> Bhasini: cleanups

config/dev.exs, lib/glific/flows/webhook.ex, lib/glific/metrics.ex, priv/repo/seeds/20200723172939_add_glific_data.exs, test/glific/flows/webhook_test.exs
=> Webhooks: Removed unique check for some urls

assets/gql/profiles/fields.frag.gql, lib/glific_web/schema/profile_types.ex, test/glific_web/schema/profile_test.exs
=> Profile: update profile type and added testcases

priv/repo/migrations/20240117234740_add_wa_groups.exs, priv/repo/migrations/20240910155519_add_separate_migration.exs
Added the DB change into separate migration file
=> Migration: seprated the new migration change into its own file

lib/glific/clients/kef.ex, lib/glific/flows/translate/export.ex
=> Metrics: Added org_id in process state preventing metric worker from crashing

lib/glific/clients/kef.ex, test/glific/clients_test.exs
=> KEF file structure updates

lib/glific/clients/kef.ex, lib/glific/third_party/openAI/chatGPT.ex, mix.exs
Target issue is #3816 
Increasing timeout for all OpenAI calls
=> OpenAI : increasing timeout for all openai calls

.github/workflows/continuous-deployment.yml, .github/workflows/continuous-integration.yml, build_scripts/gigalixir/ssh_profile.sh, lib/glific/third_party/bhasini/bhasini.ex, mix.exs, test/glific/third_party/bhasini/bhasini_test.exs
Target issue is #3822 
Converting file from `WAV` to `MP3` before uploading to GCS
=> Bhasini: File conversion

lib/glific/wa_group/wa_managed_phone.ex, lib/glific/wa_managed_phones.ex, test/glific/wa_managed_phones_test.exs
=> WA groups: populating product_id in wa_managed_phone table

lib/glific/flows.ex, lib/glific/seeds/seeds_flows.ex
added the logs for template flows
=> Template Flows: added logs for template flows

lib/glific/saas/onboard.ex, test/glific/partners/onboard_test.exs
=> Organisation: updating the suspension date after making the org active

api.docs/bruno/glific_api/SaaS/Fetch ERP organizations.bru, config/.env.dev.txt, config/runtime.exs, lib/glific.ex, lib/glific/erp.ex, lib/glific/registrations/registration.ex, lib/glific/saas/onboard.ex, lib/glific/saas/queries.ex, lib/glific_web/controllers/api/v1/onboard_controller.ex, lib/glific_web/router.ex, priv/repo/migrations/20240930061155_add_fields_in_term_and_cond.exs, test/glific/erp_test.exs, test/glific/partners/onboard_test.exs
Target issue is #3820
API to fetch the list of all the existing ngos in ERP
=> ERP next: fetch the list of orgs from ERP

lib/glific/jobs/user_jobs.ex
=> Contact Import: fetching pending user_jobs by skipping org id

lib/glific/flows.ex, lib/glific/third_party/openAI/chatGPT.ex, test/glific/flows_test.exs, test/glific_web/schema/flow_test.exs
=> Flows: List flows

lib/glific/third_party/asr/bhasini.ex
=> Bhasini: Support Longer audios

lib/glific/flows/message_vars_parser.ex, test/glific/flows/message_vars_parser_test.exs
=> Calendar: Using org Timezone

lib/glific/third_party/gigalixir.ex
=> Gigalixir: Added correct url for creating domains

lib/glific/filesearch.ex, test/glific/filesearch_test.exs
=> Assistants: Added validation for supported file formats

lib/glific/erp.ex, test/glific/erp_test.exs
=> ERPNext: updated the APIs according to recent changes

lib/glific/erp.ex, lib/glific/saas/queries.ex, lib/glific_web/controllers/api/v1/onboard_controller.ex, test/glific/erp_test.exs, test/glific/partners/onboard_test.exs
=> ERPNext: updated fixes

lib/glific/saas/queries.ex, test/glific/partners/onboard_test.exs
Target issue is #_PLEASE_TYPE_ISSUE_NUMBER_
=> ERPNext: incresed the limit of name

lib/glific/third_party/bigquery/bigquery_worker.ex
=> BQ: correct value sending for message_broadcast_contacts table

lib/glific/flows/flow_context.ex
=> Flow: Added body check in infinite loop detection

lib/glific/enums/constants/enums.ex, lib/glific/enums/enums.ex, lib/glific_web/providers/maytapi/controller/message_event_controller.ex, priv/repo/migrations/20241120104539_add_ack_types_in_message_status_enum.exs
=> WA groups: store read receipts of messages

config/.env.dev.txt, config/runtime.exs, lib/glific.ex, lib/glific/clients/common_webhook.ex, lib/glific/third_party/asr/bhasini.ex
Target issue is #3895  
- Added support for detecting language from voice notes using Bhashini
=> Bhashini: Auto Language Detection

lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex
=> GDPR: Syncing onboarding details

lib/glific/erase.ex
=> User jobs: removing old user_jobs

lib/glific/groups/wa_group.ex, lib/glific/groups/wa_groups.ex, test/glific_web/schema/contact_wa_group_test.exs
=> Wa group: update wa group name in sync api

lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex
Target issue is #3850 
Syncing all the details
=>  GDPR: Syncing all onboarding details 

lib/glific/third_party/sheets/sheets.ex, test/glific_web/schema/sheet_test.exs
=> Google sheet: Graceful handling of sheet sync errors 

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, lib/glific/third_party/sheets/sheets.ex, lib/glific_web/providers/maytapi/controller/message_event_controller.ex
Added contact_type in contacts, poll_content in wa_messages and fields in wa_groups table.
=> Bigquery: Added more fields to WA group related tables

.github/workflows/continuous-deployment.yml, build_scripts/gigalixir/ssh_profile.sh, lib/glific/third_party/bhasini/bhasini.ex
=> Revert "Bhashini: Passing mp3 as config param"

lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
=> Revert "BQ: Syncing webhook logs"

lib/glific/flows/flow_label.ex, lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
=> BQ: Syncing Flow Labels

lib/glific/third_party/bigquery/bigquery_schema.ex, lib/glific/third_party/bigquery/bigquery_worker.ex
Target issue is #3923  
Syncing User table data in the Contact table itself as user table is anyway subset of contacts table
=> BQ: Syncing Users

lib/glific/tickets/ticket.ex, test/glific/tickets_test.exs
=> Tickets: Ticket creation works even if body is empty

lib/glific/clients/common_webhook.ex, lib/glific/third_party/asr/bhasini.ex, lib/glific/third_party/bhasini/bhasini.ex, lib/glific/third_party/openAI/chatGPT.ex
Target issue is #3987  
- We removed an extra config API call for fetching models and now store them as compile-time constants, which lowers latency.
- We refactored the code and start pulling `authorization_name`, `authorization_key`, and `model_name` from the config.
- For English text-to-speech, we're using OpenAI because Bhashini’s performance wasn't great.
- Added support for choosing speech_engine between `open_ai` or `bhashini`
=> Bhashini: Optimizing speech to text

lib/glific/erase.ex, test/glific/erase_test.exs
=> GDPR: Delete Beneficiary data

lib/glific/third_party/openAI/chatGPT.ex
This is experimental PR merged to test things after removing long process sleeps
=> Filesearch: Remove process waits

lib/glific/application.ex, lib/glific/contacts/import.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, lib/glific_web/controllers/api/v1/registration_controller.ex, test/glific_web/registration_controller_test.exs, test/glific_web/schema/contact_test.exs
=> Gupshup: Removed optin api dependency

lib/glific/providers/gupshup/api_client.ex, priv/gettext/errors.pot, test/glific/partners/partners_test.exs
=> Template: migrate the sync template gupshup url

lib/glific/saas/queries.ex, lib/glific/third_party/openAI/chatGPT.ex, test/glific/partners/onboard_test.exs, test/glific/third_party/openAI/chatGPT_test.exs
=> Registration: Increased form field limits

lib/glific/clients/common_webhook.ex, lib/glific/communications/wa_group_message.ex, lib/glific/providers/maytapi/message.ex, lib/glific/providers/maytapi/wa_messages.ex, lib/glific/third_party/bigquery/bigquery.ex, lib/glific/third_party/bigquery/bigquery_worker.ex, lib/glific/wa_group/wa_message.ex, lib/glific/wa_group/wa_poll.ex, lib/glific/wa_group/wa_reaction.ex, lib/glific/wa_poll.ex, lib/glific_web/resolvers/wa_poll.ex, test/glific_web/schema/wa_poll_test.exs, test/support/fixtures.ex
=> WA Groups: Added Poll metrics

TODO.md, priv/gettext/en/LC_MESSAGES/errors.po, priv/gettext/errors.pot, priv/gettext/hi/LC_MESSAGES/errors.po
=> Legacy Code: Cleanup Chatbase

config/config.exs, priv/repo/migrations/20250224062928_pending_indexes.exs
=> Added Oban shutdown graceperiod and pending indexes

lib/glific/partners.ex, lib/glific/providers/gupshup/partner/partner_api.ex, lib/glific/providers/gupshup/wallet.ex, lib/glific_web/resolvers/contacts.ex, priv/gettext/errors.pot, test/glific/partners/partners_test.exs, test/glific_web/schema/contact_test.exs, test/glific_web/schema/provider_test.exs
=> Added Gupshup pending migrations from `/sm` endpoint

assets/gql/certificates/by_id.gql, assets/gql/certificates/count.gql, assets/gql/certificates/create.gql, assets/gql/certificates/delete.gql, assets/gql/certificates/fields.frag.gql, assets/gql/certificates/list.gql, assets/gql/certificates/update.gql, config/dev.exs, lib/glific/certificates/certificate.ex, lib/glific/certificates/certificate_template.ex, lib/glific/enums/constants/enums.ex, lib/glific/enums/ecto_enums.ex, lib/glific/enums/enums.ex, lib/glific_web/resolvers/certificate.ex, lib/glific_web/schema.ex, lib/glific_web/schema/certificate_types.ex, lib/glific_web/schema/enum_types.ex, priv/repo/migrations/20250227212728_certificate_templates.exs, test/glific_web/schema/certificate_test.exs
=> Custom certificates: certificate template APIs

lib/glific/flows/broadcast.ex, test/glific_web/schema/flow_test.exs
=> Flows: Able to run wa group flows even if gupshup credentials are inactive

lib/glific/flows/webhook.ex, lib/glific_web/flows/flow_resume_controller.ex, priv/gettext/errors.pot
- Added `call_and_wait` to skip to run flow indefinitely
- Fixed issue with results not updating due to different type of map
=> AI Platform: thread run support

.github/workflows/continuous-integration.yml, mix.exs, test/glific/processor/consumer_flow_test.exs
Trying to upgrade codecov in CI
=> test: codecov updates

test/glific/processor/consumer_flow_test.exs
=> Flaky test: Fix inactive opt-in flaky test case

lib/glific/certificates/certificate.ex, lib/glific/certificates/certificate_template.ex, lib/glific/clients/common_webhook.ex, lib/glific/third_party/google_slide/slide.ex, test/glific/flows/common_webhook_test.exs, test/glific_web/schema/certificate_test.exs
Target issue is #4092 
- Also added strict validation to slides url
=> Custom certificates: Deleting template copy and slide url validations

lib/glific/clients.ex, lib/glific/clients/sarc.ex, test/glific/clients_test.exs
=> GCS: Added custom remote url for Sarc

lib/glific_web/flows/flow_resume_controller.ex, test/glific_web/flows/flow_resume_controller_test.exs
=> AI Platform: using updated format

lib/glific/providers/gupshup/message.ex
=> Added url preview support for text messages

mix.exs
=> update mix version

mix.exs
=> build: bumped version to 7.3.3

config/config.exs, lib/glific/flows/webhook.ex, lib/glific/third_party/google_slide/slide.ex, test/glific/flows/webhook_test.exs
Target issue is https://github.com/glific/glific/issues/4313
=> Webhook: Moved custom certificate job to its own queue

lib/glific/third_party/sheets/sheets.ex
Target issue  [#4257 ](https://github.com/glific/glific/issues/4257)
=> Fix Google Sheet sync metrics

lib/glific/flows/case.ex, test/glific/flows/case_test.exs
Target issue is https://github.com/glific/glific/issues/4066
Use this flow to verify the changes introduced in this PR: [priyanshu (2).json](https://github.com/user-attachments/files/21680712/priyanshu.2.json)
=> Handle invalid regex patterns in flow execution

lib/glific/third_party/openAI/filesearch/api_client.ex
=> Remove the content-type header from upload file api

lib/glific/flows/flow_context.ex, lib/glific/flows/webhook.ex, lib/glific/flows/webhook_log.ex, lib/glific/third_party/bhasini/bhasini.ex, lib/glific/third_party/kaapi/ingest.ex, priv/gettext/errors.pot, priv/repo/migrations/20250826070711_add_flow_context_in_webhook_logs.exs, test/glific_web/providers/kaapi/action_test.exs
=> Add logs for webhook timeout failure after 60s for kaapi integration

lib/glific/clients/common_webhook.ex
context: https://discord.com/channels/1014768296257654865/1410962058991767652/1411986346066579578
=> hotfix: restore the previous call_and_wait function

mix.exs
=>  update mix version

assets/gql/organizations/get_services.gql, lib/glific/misc/flags.ex, lib/glific/partners.ex, lib/glific/partners/organization.ex, lib/glific_web/schema/organization_types.ex
adding askme bot as a feature flag
=> Add feature flag for ask me bot

lib/glific/users/user.ex, priv/repo/migrations/20250910093925_add_consent_to_users.exs, test/glific/users_test.exs
target issue: https://github.com/glific/glific/issues/4414
=> Quick Onboarding: Add constant box to the user table
